@host = 127.0.0.1:40
# @host = 192.168.1.99:8080
@token=824A109173BA6BB50D823F3633228D74
@deviceId=0d762a94-78f7-43c3-ac73-94d74df13097

### 获取菜单 
GET /nms/spring/deviceConfig/{{deviceId}}/configs/clock
# deviceType 设备类型
?type=
&token={{token}}
Host: {{host}}
Cookie:JSESSIONID={{token}}

