@h8080 = 192.168.1.80:8080

### 获取区域信息 
POST /nms/spring/role HTTP/1.1
Host: {{h8080}}
Content-Type: application/json;charset=UTF-8

{"roleName":"1","roleDesc":"2","deviceList":[{"id":"3745e4df-11f6-4565-9df8-0a06d71e4a15"}]}



