@host = 127.0.0.1:60
@token=B6B6AB41F46DFB71CAAEEF25E5634A65
@deviceId=5b1bb34c-7a10-46b3-a73d-85e0de505217


GET /nms/spring/deviceConfig/{{deviceId}}/getIoStatus?token={{token}}
&shelfIndex=0
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

###
GET /nms/spring/deviceConfig/{{deviceId}}/configs/outputRedundancyTable?token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}


### 获取设备配置信息
POST /nms/spring/deviceConfig/{{deviceId}}/getDeviceParamColl?token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

[{"node":"inputCardState","index":".1","num":""},{"node":"inputCardPriority","index":".1","num":""},{"node":"inputCardFrameType","index":".1","num":""},{"node":"inputCardCRCState","index":".1","num":""},{"node":"inputCardSSMState","index":".1","num":""},{"node":"inputCardSSMBit","index":".1","num":""},{"node":"inputCardPQL","index":".1","num":""},{"node":"inputCardCfgUsed","index":".1","num":""}]

