@host60 = 127.0.0.1:60
@token=8ACCF1A373EFE96F192068F71578CAE8


### 获取菜单 

GET /nms/spring/user/getMenu
# deviceType 设备类型
?type=deviceType
&token={{token}}
Host: {{host60}}
Cookie:JSESSIONID={{token}}







### 获取配置信息 
### 所有的设备类型（形成设备树）
### configName  配置名称 *
GET /nms/spring/systemManage/getParamConfig
# deviceType 设备类型
?type=deviceType
&token={{token}}
Host: {{host60}}
Cookie:JSESSIONID={{token}}


### 区域管理
GET /nms/spring/device/area
?token={{token}}
Host: {{host60}}
Cookie:JSESSIONID={{token}}




### 获取设备信息 
# content 具体设备信息
GET /nms/spring/device/page?token={{token}}&page=&pageSize=200&name=&ip=&deviceStatus=&areaId=&user=admin&deviceType=&NEType=&Vendor= HTTP/1.1
Host: {{host60}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}


### 获取拓扑信息

GET /nms/spring/device/netTopu?token={{token}}
Host: {{host60}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

### 保存拓扑
POST /nms/spring/device/netTopu?token={{token}}
Host: {{host60}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}



### 根据类型获取告警总数，
GET /nms/spring/report/statsnetype
Host: {{host60}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}


### 获取告警
# GET /nms/spring/alarm/activeAlarm/fliter  HTTP/1.1
# Host: {{host60}}
# token:{{token}}
# Content-Type: application/json;charset=UTF-8
# Cookie:JSESSIONID={{token}}