@host = 127.0.0.1:60
@token=54873F6B07D9366590D78364AA745DB1
@deviceId=1d295901-3745-44d5-88a6-c9e51bba5d95


GET /nms/spring/deviceConfig/{{deviceId}}/getIoStatus?token={{token}}
&shelfIndex=0
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

###
GET /nms/spring/deviceConfig/{{deviceId}}/configs/outputRedundancyTable?token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}