@host = 127.0.0.1:60
@token=BBE39E24C07016FBE8E5D64BE22A7379
@deviceId=951d1cef-08f1-4185-9b0a-e512855544bb
@deviceId2=0e575aed-32d4-4b76-b154-15f6a98a1e91


### 获取菜单信息

GET /nms/spring/user/getMenu
# deviceType 设备类型
?type=deviceType
&token={{token}}
Host: {{host}}
Cookie:JSESSIONID={{token}}


### 获取所有的设备信息 
GET /nms/spring/device/page
?page=&pageSize=200&token={{token}}&name=&ip=&deviceStatus=&deviceType=&areaId=&user=admin
&NEType=&Vendor=
Host: {{host}}
Cookie:JSESSIONID={{token}}


### 区域管理 include devices
GET /nms/spring/device/area
?token={{token}}
Host: {{host}}
Cookie:JSESSIONID={{token}}




### 获取配置信息 
### 所有的设备类型（形成设备树）
### configName  配置名称 *
GET /nms/spring/systemManage/getParamConfig
# deviceType 设备类型
?type=deviceType
&token={{token}}
Host: {{host}}
Cookie:JSESSIONID={{token}}






### 获取各区域的信息以及设备信息 children
# [area->children(device)->children(deviceEquipments info)]
#  primary Key:  device: type (judge alarmType)
GET /nms/spring/device/parents?type=all
&token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}







### network topology  to see  down 
### 获取拓扑信息

GET /nms/spring/device/netTopu?token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

### 保存拓扑
POST /nms/spring/device/netTopu?token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}
###  to see up


### 根据类型获取告警总数，
GET /nms/spring/report/statsnetype
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}


### 获取板卡信息


GET /nms/spring/deviceConfig/{{deviceId}}/getIoStatus?token={{token}}
&shelfIndex=0
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

### 同步单个设备

GET /nms/spring/device/{{deviceId}}/syncAlarms
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

### 获取报警信息
GET  /nms/spring/alarm/activeAlarm/fliter?vandor=&area=
&token={{token}}
&page=1&pageSize=1000&deviceId=&state=1%2C2&activeAlarmSource=&activeAlarmLevel=&activeAlarmReason=&activeAlarmId=&activeAlarmtimeBgn=&activeAlarmtimeEnd=&clearTimeBgn=&clearTimeEnd=&confirmTimeBgn=&confirmTimeEnd=&confirmOperator=
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}




### 获取设备的拓扑信息 (返回值根据ip ) 物理 逻辑 
# 根据ip 来获取
GET /nms/spring/viewData?areaId=
&token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}


### 新增设备

POST /nms/spring/device
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

{
    "areaId": "117c4c9f-4e09-462b-9c6e-fbb5d8be5506",
    "deviceType": "SM2000",
    "ip": "192.168.99.98",
    "name": "白广路SM2000_PRC98",
    "neType": "PRC",
    "vendor": "ss",
    "phyX": "100.86",
    "phyY": "39.25",
    "aliasName": "",
    "location": "",
    "owner": "",
    "token": "70268A44218E222A804921FD3122E905",
    "port": 0,
    "addType": "1"   // 1 物理拓扑  2  /
}


### 新增链路
## pathType 2 物理 1 逻辑拓扑
POST /nms/spring/viewData/addPath
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

{"path":{"aNe":"192.168.1.33","zNe":"192.168.99.98","pathName":"白广路SM2000_LPR,白广路SM2000_PRC98","pathType":"2","remark":""},
"pathLinkIdList":[
    {"aNode":"192.168.1.33","zNode":"192.168.99.98",
                            "aSlot":"100.86,39.25","aPort":"87.77,34.67",
                            "zSlot":"","zPort":"","linkName":"cs","linkStatus":"0","linkType":2}
]}


### 删除链路
delete  /nms/spring/viewData/deletePathByObject
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}
{"aNe":"192.168.1.33","zNe":"192.168.99.98","pathType":"2"}


### index.html  right 

#时钟类型 RPC LPR SSUT SSUL
GET /nms/spring/report/statsnetype
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

###
# 链路统计   同步链接 dom .sync-connet
GET /nms/spring/viewData/statisticsPathCount
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

#-----------down  网元组信息
### 添加网元组
POST /nms/spring/viewData/addNodeGroup
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

{
    "nodeGroup": {# 网元组信息
        "areaId": "117c4c9f-4e09-462b-9c6e-fbb5d8be5506",
        "groupName": "123",
        "xCoordinate": "100.27",
        "yCoordinate": "36.00",
        "groupAddress": "123",
        "parentId": "",
        "remark": ""
    },
    # 相关的设备列表
    "deviceIdList": ["0e575aed-32d4-4b76-b154-15f6a98a1e91", "1d295901-3745-44d5-88a6-c9e51bba5d95"]
}

### 查询所有网元组
GET /nms/spring/viewData/getAllGroup?token={{token}}

Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}


### 获取 物理拓扑 地图
GET /js/map/json/china.json?token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}


# ### 获取所有的 链路 pyhsical topo
# path 链路信息
# pathLinkIdList   

POST /nms/spring/viewData/getAllVOPath?token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

{"path":{}}





### pathType lines : logic  1 , physical 2 
GET /nms/spring/viewData/getAllPath?token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}
