@host82 = 127.0.0.1:82
# 倒叙 默认
@order_last =[{"Field": "created",  "Type": true }]  
@order_first =[{"Field": "created",  "Type": false }] 

### 历史数据上传 
POST /api/jtopo.json HTTP/1.1
Host: {{host82}}



### nms 
POST /nms/misc_info/one.json HTTP/1.1
Host: {{host82}}

{
    "query":{
        "tp":"net_topo"
    }
}
### 历史数据上传 
POST /nms/misc_info/insert.json HTTP/1.1
Host: {{host82}}

{
    "record":{
        "tp":"net_topo",
        "a":1,"b":2
    }
}


