@host = 127.0.0.1:60
@token=89CBC4781712BE50ABB39383A0B6B9B3

@host_177 = 192.168.92.177:8080
@token_177=89CBC4781712BE50ABB39383A0B6B9B3




### 
GET /nms/spring/device/syncAlarms/all?token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}



### 
GET /nms/spring/device/syncAlarms/all?token={{token_177}}
Host: {{host_177}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token_177}}




### 
GET /nms/spring/deviceConfig/configs?token={{token}}&area=
&vendor=&deviceType=SM2000&activeAlarmLevel=&page=1&pageSize=20
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}
