@host = 127.0.0.1:60
@token=CCAAAC9F409411753CE0BD76AEA4B6DA

@host_177 = 192.168.92.177:8080
@token_177=EC70CAB82449DCB66DB4A1B7C3B690C9




### 
GET /nms/spring/device/syncAlarms/all?token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}



### 
GET /nms/spring/device/syncAlarms/all?token={{token_177}}
Host: {{host_177}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token_177}}




### 
GET /nms/spring/deviceConfig/configs?token={{token}}&area=
&vendor=&deviceType=SM2000&activeAlarmLevel=&page=1&pageSize=20
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}
