@h8000 = 192.168.1.80:8000
@token="8FE3B6D069447421BECBB13722A844C7"

### 添加设备
POST /nms/spring/device HTTP/1.1
Host: {{h8000}}
Content-Type: application/json;charset=UTF-8

{"areaId":"117c4c9f-4e09-462b-9c6e-fbb5d8be5506",
"deviceType":"SM2000",
"ip":"192.168.1.22",
"name":"白广路SM2000_PRC",
"neType":"PRC",
"vendor":"ss",
"phyX":"87.51",
"phyY":"38.90",
"aliasName":"",
"location":"",
"owner":"",
"token":"5832CE02062D887F570C7EEBECC948A0",
"port":0,
"addType":"1"}