@host79 = 127.0.0.1:8079

### 历史数据上传 
POST /noise/spectrum/upload.json HTTP/1.1
Host: {{host79}}

  {
     "Token":"5771ee15a8d0241dd81378df",
     "data":{
         "sn":"1",
         "base64":"eHgxMg==",
         "t":1212
     }
}