@host = 127.0.0.1:40
# @host = 192.168.1.99:8080
@token=EBDE8172577F85C01B0418B9F4FF5028
@deviceId=0d762a94-78f7-43c3-ac73-94d74df13097

### 获取菜单 
GET /nms/spring/user/getMenu
# deviceType 设备类型
?type=
&token={{token}}
Host: {{host}}
Cookie:JSESSIONID={{token}}


### 获取配置信息 
### 所有的设备类型（形成设备树）
### configName  配置名称 *
GET /nms/spring/systemManage/getParamConfig
# deviceType 设备类型
?type=deviceType
&token={{token}}
Host: {{host}}
Cookie:JSESSIONID={{token}}


### 区域管理
GET /nms/spring/device/area
?token={{token}}
Host: {{host}}
Cookie:JSESSIONID={{token}}


### 
GET /nms/spring/deviceConfig/{{deviceId}}/configs/alarmConfigTable?token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

### 
POST /nms/spring/show/logical?token={{token}}&deviceId={{deviceId}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}




