@host = 127.0.0.1:40
@token=C2BBC3912AE20FF3B20AE781C61FB392
@deviceId=dcd44ff7-9129-4802-b456-f3f73113cdf9



### 获取单个设备的板卡信息
GET /nms/spring/deviceConfig/{{deviceId}}/getIoStatus?token={{token}}
&shelfIndex=0
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}

###
GET /nms/spring/deviceConfig/{{deviceId}}/configs/outputRedundancyTable?token={{token}}
Host: {{host}}
Content-Type: application/json;charset=UTF-8
Cookie:JSESSIONID={{token}}