@host = 127.0.0.1:40
@token=DDC5550E993B965F06C0954291F01796


### 获取菜单 
GET /nms/spring/user/getMenu
# deviceType 设备类型
?type=
&token={{token}}
Host: {{host}}
Cookie:JSESSIONID={{token}}


### 获取配置信息 
### 所有的设备类型（形成设备树）
### configName  配置名称 *
GET /nms/spring/systemManage/getParamConfig
# deviceType 设备类型
?type=deviceType
&token={{token}}
Host: {{host}}
Cookie:JSESSIONID={{token}}


### 区域管理
GET /nms/spring/device/area
?token={{token}}
Host: {{host}}
Cookie:JSESSIONID={{token}}





