routerApp.config(['$stateProvider', '$urlRouterProvider', "$translateProvider", "cfpLoadingBarProvider",function($stateProvider, $urlRouterProvider, $translateProvider, cfpLoadingBarProvider) {
    /*
        国际化  Please select
    */
    $translateProvider.translations('en', {
        MacInfo:"Mac Info",
        LinkSta:"Link State",
        LinkInfo:"Link Info",
        LinkandMac:"Link and Mac",
        MGMtime:"MGM time",
        MGMuptime:"MGM uptime",
        Image1:"Image 1",
        Image2:"Image 2",
        BackupImg:"Backup Image",
        NextImg:"Next Image",
        AlarmId : "Alarm Id",
        AlarmchrId : "Alarm Children Id",
        AlarmLevel : "Alarm Level",
        VERSIONIN:"VersionInfor",
        ENABLEOC:"EnableSwitch",
        ACTIVATE:"Activate",
        CHANEG:"Change",
        RESTART:"Restart",
        Reboot:"Reboot",
        Reset:"Reset",
        RESTARTXN:"Reset",
        RESTARTC:"RestartCard",
        PRINT:'Print',
        SORT:"Sort",
        MAP:"Map",
        ADD:"Add",
        EDIT:"Edit",
        SEARCH:"Search",
        NEXT:"NextPage",
        PREVIOUS:"PreviousPage",
        NAMECN:"Name(cn)",
        NAMEEN:"Name(en)",
        OPERATION:"Operation",
        NULL_DATA:"Null Data！",
        PLEASE_SELECT:"Please",
        activeAlarmId : "Active Alarm Id",
        activeAlarmModule : "Active Alarm Module",
        activeAlarmLevel : "Active Alarm Level",
        time : "Time",
        isEnable : "Is Enable",
        urgentAlarm : "Critical",
        mainAlarm : "Major",
        minorAlarm : "Minor",
        EVENT : "Event",
        MAIL:'Mail',
        DISABLE:"Disable",
        ENABLE:'Enable',
        BACK:'Back',
        CONFIRM:"Confirm",
        ALARM_FILTER:"Alarmfilter",
        SEND:'Send',
        NO_SEND:"NoSend",
        ALARM_LOG:"AlarmLog",
        DEVICE:'Device',
        STATE:"State",
        BEGIN_TIME:"BeginTime",
        END_TIME:"EndTime",
        SHOW_DATE:"DisplayDate",
        OPERATION_TIME:"OperationTime",
        ALARM_BEGIN_TIME:"AlarmTime",
        ALARM_END_TIME:"AlarmTime",
        CLEAR_BEGIN_TIME:"ClearTime",
        CLEAR_END_TIME:"ClearTime",
        CONFIRM_BEGIN_TIME:"ConfirmTime",
        CONFIRM_END_TIME:"ConfirmTime",
        ALARM_REASON:"AlarmMessage",
        ALARM_CONFIRMATION:'AlarmConfirmation',
        DISAPPEAR:'Disappear',
        PRODUCE:"Produce",
        CLEAR:"Clear",
        ALARM_TIME:'AlarmTime',
        CONFIRM_TIME:'ConfirmTime',
        CLEAR_TIME:'ClearTime',
        DESCRIBE:"Describe",
        SYSTEM_NAME:'SystemName',
        SYSTEM_LOG:'SystemLog',
        OPERATION_LOG:'OperationLog',
        USER:'User',
        NETWORK_LOG:'NetworkLog',
        ALARM_CONTENT:"AlarmMessage",
        SAFE_LOG:'SafeLog',
        PERFORMANCE_LOG:"PerformanceLog",
        TYPE:'Type',
        PORT:'Port',
        VALUE:'Value',
        AREA_MANAGE:'Area Manage',
        AREA_NAME:'Area Name',
        AREA_ADD:'Area Add',
        DEVICE_MANAGE:'Device Manage',
        ALLOCATION : "Allocation",
        ALREADY_ASSIGEND:"Assigned",
        Not_ASSIGNED:"No Assigned",
        ARER:'Area',
        NE_NAME:"NE Name",
        NE_IP:"NE IP",
        Previous_NE:"Previous NE",
        Next_NE:"Next NE",
        NE_add:"NE Address",
        NE_DESCRIBE:"NE Describe",
        NE_VERSION:"NE Version",
        NE_TIME:"NE Time",
        NE_TYPE:'NE Type',
        NE_PHYSICAL_POSSITION:"NE Physical Position",
        NE_SUPPLIER_NAME:"NE Supplier Name",
        AREA_CHOOSE:"Area Choose",
        Choose_Port:"ChoosePort",
        Time_Sync:"TimeSync",
        Time_Zone:"TimeZone",
        Server_Alarm_Threshold:"ServerAlarmThreshold",
        Alarm_Threshold:"AlarmThreshold",
        Database_Config:"DatabaseConfig",
        NE_AND_NETWORK_connection:'NE And Network Connection',
        NE_LOCAL_NAME:"NE Local Name",
        RECK_FRIENDLY_NAME:"Rack Friendly Name",
        RECK_LOCAL_NAME:"Rack Local Name",
        RECK_IDENTIFIER:"Rack Identifier",
        MAP_CUSTOM:"Map Custom",
        MANUAL_BACKUP_ARCHIVE:"Manual Backup/archive",
        ARCHIVE:'Archive',
        BACKUP:'Backup',
        RESTORE:"Restore",
        TABLE_NAME:"TableName",
        SUBCLASS:'SubClass',
        DATA_DEADLINE:"Data Deadline",
        FILE_PATH:'File Path',
        BACKUP_ARCHIVE_POLICY:'Backup/archive Policy',
        MAX_DATA_VOLUME:'MAX Data Volume',
        MAX_STORAGE_MONTH:'MAX Storage Month',
        BACKUP_TYPE:'BackupType',
        STORAGE_PATH:'StoragePath',
        BACKUP_ARCHIVE_RECORDS:"Backup/archive Records",
        HARDWARE_VERSION:"HardwareVersion",
        MEMORY:"Memory",
        PROCESSOR:"Processor",
        GRAPHICAL:"Graphical",
        DISK:"Disk",
        PID:"PID",
        CPU:"CPU",
        MEM:"MEM",
        VSZ :"VSZ",
        RSS :"RSS",
        RUN_STATE:"RunningState",
        START:"Start",
        STOP:"Stop",
        STARTs:"Starts",
        End:"End",
        RUN_TIME :"RunningTime",
        COMMAND:"Command",
        SOFTWARE_PROCESS_INFORMATION:"Software Process Information",
        SOFTWARE_VERSION:"Software Version",
        ASSEMBLY:"Assembly",
        ASSEMBLY_NAME:'AssemblyName',
        VERSION:'Version',
        DATABASE:'Database',
        CACHE:"Cache",
        WEB_SERVER:"WebServer",
        REVERSE_PROXY:"ReverseProxy",
        ftp_SERVER:"FTPServer",
        DEVICE_TOPOLOGY : "DeviceTopology",
        DEVICE_TIME:"deviceTime",
        DEVICE_TIMEBG:"UTC+8",
        DEVICE_NAME:"DeviceName",
        DEVICE_IP:"DeviceIP",
        REFERENCE_MODEL:"Reference Model",
        REFERENCE_Criteria:"Reference Criteria",
        CURRENT_REFERENCE:"Current Reference",
        CLOCK_STATE:"Clock State",
        ZONCA_1_STATE:"CC1 State",
        ZONCA_2_STATE:"CC2 State",
        CCStatus:"CC Status",
        MACHINE_FRAME:"Shelf",
        SLOT_NUMBER:"Slot Number",
        IO_type:"I/O type",
        SIGNAL_TYPE:"Signal Type",
        REDUNDANCY_ENABLE:"Redundancy Enable",
        MAIN_CARD:"Active Card",
        EPISODE_RULES:"Episode Rules",
        MONITORING_PERIOD : "Monitoring Period(s)",
        MONITORING_STATE : "Monitoring State",
        MONITORING_BEGIN_TIME : "Monitoring Begin Time",
        MONITORING_END_TIME : "Monitoring End Time",
        WHETHER_AUTOMATIC_REPORTING:"Whether Automatic Reporting",
        ORDER:'Order',
        USERNAME:'User Name',
        PASSWORD:"Password",
        GNSS1_ENABLE :"Enable",
        GNSS1_PATTERN : "Pattern",
        LONGITUDE : "Longitude",
        LATITUDE : "Latitude",
        HEIGHT : "Height",
        TRACKING_MODE : "Tracking Mode",
        ANTENNA_DELAY : "Antenna Delay",
        PQL_STATE :"PQL State",
        PQL_VALUE : "PQL Value",
        SET: "Set",
        CURRENT_DEVICE : "CurrentDevice",
        PORT_ENABLE : "Port Enable",
        SLOT : "Slot",
        INPUT_CARD : "InputCard",
        PRIORITY : "Priority",
        TTL : "TTL",
        DSCP : "DSCP",
        PacketLimit : "Packet Limit",
        ProbeEnable : "Probe enable",
        ServerIP : "Server IP",
        Interval : "Interval",
        DSCPENABLE : "DSCP Enable",
        StatusENABLE : "Status Enable",
        Mode : "Mode",
        LeapStatus : "Leap Status",
        StratumLevel : "Stratum Level",
        RootDispersion : "Root Dispersion",
        PacketLoad : "Packet Load",
        Sync : "Sync",
        offset : "offset",
        offsetfw : "offset(>0.01 or <-0.01)",
        ANN : "Announce",
        UnicastClinet : "UnicastClient",
        ClockID : "Clock ID",
        Grandmasterip : "Grandmaster IP",
        Grandmasterid : "Grandmaster Clock ID",
        LeaseDuration : "Lease Duration",
        Profile : "Profile",
        TimeScale : "Time Scale",
        Domain : "Domain",
        SyncLimit  : "Sync Limit",
        DelayLimit : "Delay Limit",
        TwoStep : "Two Step",
        UnicastNegotiation : "Unicast Negotiation",
        AnnounceLimit : "Announce Limit",
        AlternateMaster : "Alternate Master",
        UnicastLeaseDuration  : "Unicast Lease Duration",
        SyncInterval : "Sync Interval",
        AnnounceInterval : "Announce Interval",
        DelayInterval  : "Delay Interval",
        AnnounceTimeout : "Announce Timeout",
        ClientTimeout : "Client Timeout",
        GatewayNetxHop  : "Gateway/NetxHop",
        ActiveImage  : "Active Image",
        ActiveVersion : "Active Version",
        imageBackupImage : "Backup Image",
        imageBackupVersion : "Backup Version",
        imageCurrentImage : "Next Boot Image",
        imagebootImage : "Next Boot Image",
        outputNTPchangeActiveStatus : "OutputNTPchange ActiveStatus",
        broadcastConfig : "Broadcast Config",
        outputNTPbroadcastState : "Output NTPbroadcast State",
        outputNTPbroadcastIP : "Output NTPbroadcast IP",
        outputNTPbroadcastInterval : "Output NTP Broadcast Interval",
        outputNTPbroadcastConfig : "Output NTP Broadcast Config",
        CableDelay : "Cable Delay",
        FRAME_TYPE : "Frame Type",
        CRC_STATE : "CRC State",
        SSM_STATE : "SSM State",
        SSM_BIT: "SSM Bit",
        QUALITY_GRADE:"Quality Grade",
        SYSTEM_TIME : "System Time",
        LEAP_SECONDS_SET : "LeapSeconds Set",
        NTP_ENABLE : "NTP Enable",
        DATA_FORMAT : "Data Format",
        MAX_CLIENT : "MAX Client",
        MANAGED_ADDRESS_MODE:"Managed Address Mode",
        INDEX : "Index",
        ADDRESS : "Address",
        ALARM_DELAY: "Alarm Delay",
        ALARM_ENABLE: "Alarm Enable",
        ALARM_DESC : "Alarm Description",
        LEVEL : 'Level',
        DELAY : "Delay",
        REPORT_ENABLE: "Report Enable",
        REPORT_ENABLEA: "Report Enable(ALL)",
        MANAGEMENT_CARD : "Management Card",
        CARD_1 : 'Clock Card1',
        CARD_2 : 'Clock Card2',
        IP_ADDRESS:"IP Address",
        MASK :"Mask",
        GATEWAY: "Gateway",
        DestNetwork: "Dest Network",
        FIREWALL_TYPE: "Firewall Type",
        FIREWALL_State: "Firewall State",
        PORT_1_MODEL: "Port1 Business Model",
        PORT_2_MODEL: "Port2 Business Model",
        IP_PORT_STATE: "IP Port State",
        IP_MODE:"IP Mode",
        CURRENT_RATE:"Current Rate",
        AUTO_NEGO_ENABLE:"Automatic Negotiation Enable",
        AUTO_NEGO_rATE:"Automatic Negotiation Rate",
        VLAN_MODE_ENABLE:"VLAN Mode Enable",
        NUMBER:'Number',
        TARGET_IP: "Target IP",
        ZCARD_1_CUR_STATE:"The Current state of card 1",
        ZCARD_2_CUR_STATE:"The Current state of card 2",
        MODULAR:"Modular",
        CARD_TYPE:"Card Type",
        ClEI_NUMBER:"ClEI Number",
        SERIAL_NUMBER:"Serial Number",
        FRGA_VERSION:'FPGA Version',
        SOUND : 'Sound',
        SOUND_SWITCH : "Sound switch",
        SOUND_INTERVAL : "Sound Interval",
        SOUND_RESPONSE_TIME : "Single Response Time",
        SCREENSAVER : "Screensaver",
        SCREENSAVER_SWITCH : "ScreenSaver Switch",
        WAKE_PASSWORD_SWITCH : "Wake Password Switch",
        WAITING_TIME : "Waiting Time",
        WAKE_PASSWORD : "Wake Password",
        DEVICE_TESTING : "Device Testing",
        MODE:'Mode',
        INPUT: "Input",
        TESTING : "Testing",
        NETWORK_UPGRADE:"Network Upgrade",
        LANGUAGE : "Language",
        PERFORMANCE_FORM : "Performance Form",
        PERFORMANCE_MONITORING_CONFIGURATION:"Performance Monitoring Configuration",
        EXPORT:"Export",
        BOARD_CARD:'Board Card',
        BACKUP_TO: "Backup to",
        CLOCK_CARD:'Clock Card',
        CPMR:"CPMR",
        CLOCK_CARD1:'Clock Card1',
        CLOCK_CARD2:'Clock Card2',
        MANAGE_CARD:"Manage Card",
        OAM:"OAM",
        ALL_BOARD_CARD:'All BoardCard',
        CONFIGURATION_FILE:"ConfigurationFile",
        REMOTE_IP:"Remote IP",
        FILE:'File',
        DEVICE_C_B_R:"Device Configuration Backup And Restore",
        DEVCIE_UPGRADE : "Equipment Upgrade",
        UPGRADE_F_N_FORMAT:"Upgrade File Name",
        FTP_SERVER_IP:'FTP Server IP',
        YES:'Yes',
        NO:'No',
        EXIT:'Exit',
        CURRENT_USER:"Current User",
        DELETE:'Delete',
        ALARM:"Alarm",
        CHECK:'Check',
        REFERENCE:"Reference",
        MAINSHELF:"MainShelf",
        EXPSHELF1:"ExpShelf1",
        EXPSHELF2:"ExpShelf2",
        EXPSHELF3:"ExpShelf3",
        EXPSHELF4:"ExpShelf4",
        CARPER:"Board(%)",
        CPUME:"CPU and Memory",
        EXPPER:"Slot(%)",
        CHOOSE:"Choose",
        CURRENT:"Current Device",
        NTP_ENABLE : "NTP enable",
        DITHER : "Dither",
        SERVICEMODE : "ServiceMode",
        PRIORITY1 : "Priority1",
        PRIORITY2 : "Priority2",
        DSCP_ENABLE : "DSCP Enable",
        ESMC_ENABLE : "ESMC Mode Enable",
        SynceQL_ENABLE : "SynceQL Mode Enable",
        SynceOutQLmode : "SynceOutQL Mode",
        AutoNeg_ENABLE : "AutoNeg Enable",
        DUPLEX : "Duplex",
        RATE : "Rate",
        PTPPORT_ENABLE : "Port Enabled",
        PTPCLOCKID : "ClockID",
        PTPPROFILE : "Profile",
        PTPCLOCKSTATE : "Clock State",
        CURRENTTIME : "CurrentTime",
        RUNNINGTIME : "RunningTime",
        PTPPORTSTATE : "Port State",
        PTPCLOCKCLASS : "Clock Class",
        PTPCLOCKACCURACY : "Clock Accuracy",
        PTPTIMESCALE : "Timescale",
        PTPCLIENTNUM : "ClientNum",
        PTPCLINETLOAD : "ClientLoad",
        PTPNETWORKHWADDR : "NetworkHWAddr",
        MD5_ENABLE : "MD5 enable",
        MD5TIMESCALE : "MD5Timescale",
        Autokey_ENABLE : "Autokey enable",
        AutokeyTIMESCALE : "Autokey TIMESCALE",
        ntpList_ENABLE : "NtpList enable",
        RESTORESETTING : "Restore settings",
        backupConfig : "Backup settings",
        DEFAULTSETTING : "Default settings",
        FACTORYSETTING : "Factory settings",
        RESTORE : "Restore",
        OPENWHITELIST : "Open the whitelist",
        OPENBLACKLIST : "Open the blacklist",
        USERMANAGEMENT : "User Management",
        MENUROLE : "Menu Role",
        DEVICEROLE : "Device Role",
        ROLE : "Role",
        EQUIPMENTDISTRIBUTION : "Equipment Distribution",
        ROLENAME : "Role Name",
        ROLEMANAGEMENT : "Role Management",
        MENUMANAGEMENT : "Menu Management",
        MENUDISTRIBUTION : "Menu Distribution",
        MENULEVEL : "Menu Level",
        ROUTE : "Route",
        LEAFNODE : "Leaf Node",
        EDITMENU : "Edit Menu",
        ADDNEXTMENU : "Add Next Menu",
        ADDFIRSITMENU : "Add First Menu",
        SAVE : "Save",
        REAL_TIME_ALARM:"Real time Alarm",
        CONFIRM_VIEW:"Confirm view",
        CONFIRM_CLEAR:"Confirm clear",
        REFERENCE_STATE:"Reference State",
        QL_STATE:"QL state",
        QL_CONFIG:"QL configuration",
        QL_VALUE:"QL value",
        MANUFCATURER:"ManuFacturer",
        PRODUCT_NAME:"Product Name",
        HARDWARE:"HardWare",
        AZIMUTH:"Azimuth",
        ELEVATION:"Elevation",
        NO_OFFECTVE_SATELLITE:"No effective satellite",
        PAGE:'Page',
        TO_:'To',
        TOTALE:"Total",
        logSize:"",
        SAISI:"NMS",
        MANAGEMENTNETWORK:"Network",
        PTPOUTPUTCARD:"PTP OutputCard",
        E1OUTPUTCARD:"E1outputcard",
        PPSTODOUTPUTCARD:"PPS-TOD outputcard",
        SAISIVERSION:"ZhejiangSaisi Version",
        LOGIN:"Login",
        FORMATO:"Format one",
        FORMATT:"Format two",
        TARGETIP:"Target IP",
        INVENTORYINFO:"InventoryInfo",
        CURRENTSHELF:"Current shelf",
        CUR_STATE:"Current state",
        CUR_INFO:"UserInfor",
        DOWNLOAD:"Download",
        OTHER:"Other",
        ALARM_STATE:"Alarm Status",
        ALARM_CONFIG:"Alarm Config",
        BOARDCAST:"Boardcast",
        IMAGE:"Image",
        IOPUT:"I/O",
        UPGRADE:"Upgrade",
        INVENTORYGROUP:"InventoryGroup",
        NETWORK:"Network",
        BLACKLIST:"Ntp Blacklist",
        WHITELIST:"Ntp Whitelist",
        SERVER:"Ntp Server",
        NTPUSER:"Ntp User",
        REFHISTORY:"RefOffsetHistory",
        UPGRADE:"Upgrade",
        NEW_PASSWORD:"New Password",
        CONFIRM_N_PAS:"Confirm newPassword",
        D_I_C_Number:"Does it contain numbers",
        PASSWORD_LEN:"Password length",
        W_T_P_COMP:"Whether To Set The Password Vomplexity\n",
        D_I_C_s_c:"Does it contain Special character",
        D_I_C_E_CASE:"Does it contain English case",
        P_E_DATAS:"Password Expiration Days",
        GETLIST:"getList",
        PASSWORDRULE:"Password Rule",
        NE_CONTDE:"NE State",
        ONLINE:"On Line",
        OFFLINE:"Off Line",
        VERSION_sync: "VersionSync",
        OUPUT: "OutputCard",
        NTPCONFIG: "NTP Config",
        NTPPROBE: "NTP Probe",
        NTPSTATUS: "NTP Status",
        PTPCommon: "PTP Common",
        PTPMulticast: "PTP Multicast",
        PTPUnicast: "PTP Unicast",
        PTPProbe: "PTP Probe",
        ALARM_CONFIGSUB: "AlarmModlesub",
        CONFIG: "Config",
        AUTHENTICA: "Authentica",
        NTPMD5VALUE: "Ntp Md5 Value",
        MD5State: "MD5 State",
        AutokeyState: "Autokey State",
        refConfigTable: "RefConfig Table",
        refOffsetHistoryTable: "RefOffset History Table",
        PartNum: "PartNum",
        SerialNum: "SerialNum",
        CLEINum: "CLEINum",
        HwNum: "HwNum",
        SwNum: "SwNum",
        FPGAVersion: "FPGAVersion",
        CompatibilityNum: "CompatibilityNum",
        GeneralStatusMEMload: "General StatusMEM load",
        GeneralStatusCPUload: "General StatusCPU load",
        clockCurrentTime: "Clock Current Time",
        clockRunningTime: "Clock Running Time",
        clockState: "Clock State",
        IpState: "Ip State",
        HWAddr: "HWAddr",
        AutoNegState: "Auto NegState",
        Speed: "Speed",
        Ipv6Info: "Ipv6 Info",
        PTPnonelist: "None",
        PTPBlacklist: "NTP Blacklist",
        PTPWhitelist: "NTP Whitelist",
        SyncE: "Synce",
        SyncEConfig: "SynceConfig",
        SyncEStatus: "SynceStatus",
        EthMode: "Eth Mode",
        TXssm: "TXssm",
        ScaledLogVariance: "ScaledLogVariance",
        TimeSource: "Time Source",
        CurrUtcOffset: "CurrUtcOffset",
        MD5key: "MD5 key",
        Chinese: "Chinese",
        English: "English",
        Selectupgradefile: "Select Upgrade File",
        Name: "Name",
        Progress: "Progress",
        Actions: "Actions",
        configName: "Config Name",
        comment1: "Comment1",
        comment2: "Comment2",
        comment3: "Comment3",
        Upload: "Upload",
        Cancel: "Cancel",
        Remove: "Remove",
        alarmsNum: "Alarm Num",
        deviceType: "DeviceType",
        binding: "Binding",
        portName: "PortName",
        bordtype: "Bord type",
        remarks: "Remarks",
        ntpServerListEnable: "ListEnable",
        ntpServerAutoKeyEnable: "AutoKeyEnable",
        ntpServerAutoKeyValue:"AutoKeyValue",
        ntpServerBroadcastEnable:"BroadcastEnable",
        ntpServerBroadcastAddr:"BroadcastAddr",
        ntpServerBroadcastInterval:"BroadcastInterval",
        ntpServerMd5Enable:"Md5Enable",
        ntpServerMd5Value:"Md5Value",
        ntpServerManycastEnable:"ManycastEnable",
        ntpServerManycastAddr:"ManycastAddr",
        ntpServerManycastInterval:"ManycastInterval",
        ntpServerConfigPortState:"ConfigPortState",
        ntpServerConfig:"NTPServer Config",
        ntpAutoKeyEnable:"NtpAutoKeyEnable",
        ntpAutoKeyValue:"NtpAutoKeyValue",
        ntpBroadcastEnable:"NtpBroadcastEnable",
        ntpBroadcastAddr:"NtpBroadcastAddr",
        ntpBroadcastInterval:"NtpBroadcastInterval",
        ntpEnable:"NtpEnable",
        ntpMd5Enable:"NtpMd5Enable",
        ntpManycastEnable:"NtpManycastEnable",
        ntpManycastAddr:"NtpManycastAddr",
        ntpManycastInterval:"NtpManycastInterval",
        refOffsetHistoryShowFlag:"RefOffsetHistoryShowFlag",
        refOffsetHistoryShowNumber :"RefOffsetHistoryShowNumber ",
        refOffsetHistoryInfo:"RefOffsetHistoryInfo",
        refConfigType:"RefConfigType",
        refActive:"RefActive",
        refState:"RefState",
        refPriority:"RefPriority",
        refQuality:"RefQuality",
        invAssetNum:"InvAssetNum",
        invSystemModel:"InvSystemModel",
        invPartNum:"InvPartNum",
        invClEINum:"InvClEINum",
        invSerial:"InvSerial",
        invHWVersion:"InvHWVersion",
        invSWVersion:"InvSWVersion",
        gpsConfigMode:"GpsConfigMode",
        gpsConfigElevMask:"GpsConfigElevMask",
        gpsConfigCableDelay:"GpsConfigCableDelay",
        gnssConfigMode:"GnssConfigMode",
        gnssConfigElevMask:"GnssConfigElevMask",
        gnssConfigCableDelay:"GnssConfigCableDelay",
        gnssConfigTrackMode:"gGnssConfigTrackMode",
        tftpServerAddress:"Tftp Server Address",
        todSource:"Tod Source",
        lcdTimeZone:"Time Zone",
        lcdTimeZonec:"Time Zone",
        activeAlarms:"Active Alarms",
        NMSAlarms:"NMS Alarms",
        Alarm_Tip_Filter:"Alarm Tip Filter",
        About:"About",
        Help:"Help",
        ref:"Ref",
        systemName:"System Name",
        systemStatus:"System Status",
        systemTime:"System Time",
        systemUptime:"System Uptime",
        outputSquelchState: "Output Squelch State",
        outputPPSState: "Output PPS State",
        output10MState: "Output 10M State",
        outputrefidleapState: "outputrefidleapState",
        imageVersion: "ImageVersion",
        imageInfoIndex: "ImageInfoIndex",
        systemReboot: "System Reboot",
        noapply: "NoApply",
        apply: "Apply",
        Manual: "Manual",
        Auto: "Auto",
        backupIPCConfig: "BackupIPCConfig",
        factoryIPCConfig: "FactoryIPCConfig",
        restoreIPCConfig: "RestoreIPCConfig",
        rebootIPC: "RebootIPC",
        tail: "Tail",
        head: "Head",
        all: "All",
        gpsSatelliteSNR: "GpsSatelliteSNR",
        gpsSatelliteAZIM: "GpsSatelliteAZIM",
        gpsSatelliteIndex: "GpsSatelliteIndex",
        gpsSatelliteELEV: "GpsSatelliteELEV",
        gpsStaTrackStatue: "GpsStaTrackStatue",
        gpsProducer: "GpsProducer",
        gpsStaCurrentPosition: "GpsStaCurrentPosition",
        gpsSatelliteNumber: "GpsSatelliteNumber",
        gpsSatellitePRN: "GpsSatellitePRN",
        gnssStaEngineModel: "GnssStaEngineModel",
        gnssStaPpsRef: "GnssStaPpsRef",
        gnssStaPpsValid: "GnssStaPpsValid",
        gnssStaPOSMode: "GnssStaPOSMode",
        iocstatus: "Clock Status",
        PTPstatus: "PTP status",
        netstatus: "Network Status",
        ioccomm: "Ioccomm",
        imccomm: "Imccomm",
        iocstate: "Iocstate",
        INSERV: "INSERV",
        OOSRV: "OOSRV",
        iocmode: "Iocmode",
        ACTIVE: "Active",
        STANDBY: "Standby",
        ACTIVEBY: "Active",
        clkmode: "Clkmode",
        WARMUP: "WARMUP",
        FREERUN: "FREERUN",
        FASTLOCK: "FASTLOCK",
        BRIDGING: "BRIDGING",
        HOLDOVER: "HOLDOVER",
        LOCKED: "LOCKED",
        clktype: "Clktype",
        ST3E: "ST3E",
        TYPEI: "TYPEI",
        ST2: "ST2",
        TYPEII: "TYPEII",
        outstatus: "outstatus",
        OK: "OK",
        ALM: "ALM",
        UNEQUIPPED: "UNEQUIPPED",
        outstate: "outstate",
        frmtype: "frmtype",
        freeflt: "freeflt",
        holdflt: "holdflt",
        gpsstatus: "gpsstatus",
        mode: "MODE",
        pos: "POS",
        elevmask: "elevmask",
        satelliteList: "satelliteList",
        inpstatus: "inpstatus",
        instate: "instate",
        MONITOR: "MONITOR",
        qlevel: "qlevel",
        refModel: "refModel",
        rqlevel: "rqlevel",
        crcena: "crcena",
        ssmena: "ssmena",
        ssmbit: "ssmbit",
        ioc1comm: "ioc1comm",
        ioc2comm: "ioc2comm",
        baud: "baud",
        flow: "flow",
        NONE: "NONE",
        SW: "SW",
        HW: "HW",
        SWHW: "SWHW",
        ipsubnet: "ipsubnet",
        echo: "echo",
        outstatus: "outstatus",
        outstate: "outstate",
        prsstatus: "prsstatus",
        aid: "aid",
        ntfcncde: "ntfcncde",
        condtype: "condtype",
        authen: "authen",
        keyid: "keyid",
        minpoll: "minpoll",
        maxpoll: "maxpoll",
        preferred: "preferred",
        rtmstatus: "rtmstatus",
        rtmstate: "rtmstate",
        rtmlbo: "rtmlbo",
        RETIME: "RETIME",
        CUTTHRU: "CUTTHRU",
        rtmslip: "rtmslip",
        syncmode: "syncmode",
        refmode: "refmode",
        imc: "imc",
        coml: "coml",
        comr: "comr",
        comi: "comi",
        ON: "ON",
        SQUELCH: "SQUELCH",
        Fasttrack: "Fasttrack",
        State: "State",
        alarmmode: "alarm mode",
        systemParameter: "system Parameter",
        aomerge: "aomerge",
        inacttime: "inacttime",
        lclao: "lclao",
        ALWAYS: "ALWAYS",
        LOGIN: "Login",
        NEVER: "NEVER",
        lclbaud: "lclbaud",
        Y: "Y",
        N: "N",
        lclflow: "lclflow",
        lclecho: "lclecho",
        rmtao: "rmtao",
        rptall: "rptall",
        scramble: "scramble",
        AIS: "AIS",
        hldact: "hldact",
        CONTINUE: "CONTINUE",
        sabits: "sabits",
        BITS:"BITS",
        traffic: "traffic",
        trscssm: "trscssm",
        INSERT: "INSERT",
        NOINSERT: "NOINSERT",
        loslog: "loslog",
        losalm: "losalm",
        NONALM: "NONALM",
        cri: "cri",
        rpt: "rpt",
        pm: "pm",
        thr: "thr",
        isqlog: "isqlog",
        isqalm: "isqalm",
        hslimit: "hslimit",
        bldlmt: "bldlmt",
        dsctime: "dsctime",
        hfqlevl: "hfqlevl",
        hfqlevlsec: "hfqlevlsec",
        manchan: "manchan",
        mxccn: "mxccn",
        pirange: "pirange",
        pirangesec: "pirangesec",
        sprdchn: "sprdchn",
        wtrss: "wtrss",
        revert: "revert",
        syncmde: "syncmde",
        FORCED: "FORCED",
        tconstsec: "tconstsec",
        autopm: "autopm",
        crc4: "crc4",
        ctieenb: "ctieenb",
        currssm: "currssm",
        format: "format",
        measdly: "measdly",
        monitor: "monitor",
        prc5MHZ: "prc5MHZ",
        qcutoff: "qcutoff",
        sigmode: "sigmode",
        ssmenb: "ssmenb",
        ssmpdh: "ssmpdh",
        tconst: "tconst",
        IMCStateEvent: "IMC State Event",
        TransientEvent: "Transient Event",
        InputStateEvent: "Input State Event",
        ITHStateEvent: "ITH State Event",
        SubrackorIMCNIMCStateEvent: "Subrack or IMC/NIMC State Event",
        NIMCEvent: "NIMC Event",
        OutputCardStateEvent: "Output Card State Event",
        StateEvent: "State Event",
        IMCNIMCStateEvent: "IMC/NIMC State Event",
        timeDate: "timeDate",
        module: "module",
        status: "Status",
        threshold: "Threshold",
        ntpAutokeyfileSetting: "ntpAutokeyfileSetting",
        ntpMD5keySetting: "ntpMD5keySetting",
        inputSourceType: "inputSourceType",
        inputSourceState: "inputSourceState",
        outputIrigbAcRatio: "outputIrigbAcRatio",
        outputIrigbConfig: "outputIrigbConfig",
        outputIrigbOffset: "outputIrigbOffset",
        outputIrigbParity: "outputIrigbParity",
        outputTodSelect: "outputTodSelect",
        refStatusType: "refStatusType",
        refStatusFreqSt: "refStatusFreqSt",
        refStatusFreqWeight: "refStatusFreqWeight",
        refStatusTimeSt: "refStatusTimeSt",
        refStatusTimeWeight: "refStatusTimeWeight",
        refStatusQlF: "refStatusQlF",
        refStatusQlT: "refStatusQlT",
        refConfigFP: "refConfigFP",
        refConfigF: "refConfigF",
        refConfigTP: "refConfigTP",
        refConfigT: "refConfigT",
        refConfigAQL: "refConfigAQL",
        refConfigFAQL: "refConfigFAQL",
        refConfigTAQL: "refConfigTAQL",
        ntpSlotAlarm: "ntpSlotAlarm",
        ntpSlotCpuMem: "ntpSlotCpuMem",
        ntpSlotHWVersion: "ntpSlotHWVersion",
        ntpSlotImage: "ntpSlotImage",
        ntpSlotLinkStatus: "ntpSlotLinkStatus",
        ntpSlotMacInfo: "ntpSlotMacInfo",
        ntpSlotTrackStatus: "ntpSlotTrackStatus",
        ntpSlotVersionInfo: "ntpSlotVersionInfo",
        ntpSlotBackup: "ntpSlotBackup",
        ntpSlotReboot: "ntpSlotReboot",
        ntpSlotRestore: "ntpSlotRestore",
        ntpPortByteEn: "ntpPortByteEn",
        ntpPortAutokeyEn: "ntpPortAutokeyEn",
        ntpPortAutokeyVal: "ntpPortAutokeyVal",
        ntpPortIpAddr: "ntpPortIpAddr",
        ntpPortIpEn: "ntpPortIpEn",
        ntpPortListIp: "ntpPortListIp",
        ntpPortListMode: "ntpPortListMode",
        ntpPortMd5En: "ntpPortMd5En",
        ntpPortMd5Val: "ntpPortMd5Val",
        ntpPortMode: "ntpPortMode",
        ntpPortPing: "ntpPortPing",
        ntpPortPingResult: "ntpPortPingResult",
        ntpPortBroadcastAddr: "ntpPortBroadcastAddr",
        ntpPortBroadcastCfg: "ntpPortBroadcastCfg",
        ntpPortBroadcastEn: "ntpPortBroadcastEn",
        ntpPortBroadcastTimeInterval: "ntpPortBroadcastTimeInterval",
        ntpPortRate: "ntpPortRate",
        ntpPortReset: "ntpPortReset",
        ntpPortResetResult: "ntpPortResetResult",
        referencePtpin: "referencePtpin",
        refStatePtpin: "refStatePtpin",
        refPriorityPtpin: "refPriorityPtpin",
        refStatusPtpin: "refStatusPtpin",
        slotNumber: "slotNumber",
        NtpSlot: "NtpSlot",
        NtpPort: "NtpPort",
        cardType: "cardType",
        outputSignal: "outputSignal",
        slotState: "slotState",
        powerState: "powerState",
        halfDuplex: "halfDuplex",
        fullDuplex: "fullDuplex",
        baseConfig: "BaseConfig",
        Terminal: "Terminal",
        PortBZ: "Port Name",
        ConfigManage: "Config Manage",
        Client: "Client",
        Common: "Common",
        GM1addr: "GM1addr",
        GM1state: "GM1state", 
        GM2state: "GM2state", 
        GM2addr: "GM2addr",
        FLLstate: "FLLstatus", 
        ForwardFlowWeight: "Forward Flow Weight", 
        ReverseFlowWeight: "Reverse Flow Weight", 
        CorrectionFrequency: "Correction Frequency",
        PhaseCorrection: "Phase Correction",
        ResidualPhaseError: "Residual Phase Error",
        MinimalRTD: "Minimal RTD",
        PacketRateGM1: "Packet Rate GM1",
        PacketRateDelay: "Packet Rate Delay",
        ClientConfigState: "Client Config State",
        UTCTIME: "UTC Time",
        BJTIME: "Beijing Time",
        qyjx: "Area Shorthand",
        qycj: "Area Level",
        srdk: "Input Port",
        srcw: "Input Slot",
        scdk: "Output Port",
        sccw: "Output Slot",
        pslotport: "Please Input Slot and Port",
        noalarm: "None",
        xxlx: "Signal Flow Direction:",
        delDirection: "Delete",
        COPYTO: "Copy To",
        SHOWALL: "Show All",
        Input1: "Input 1",
        Input2: "Input 2",
        PTPoutput: "PTP Output",
        PTPInput: "PTP Input",
        NTPoutput: "NTP Output",
        E1output: "E1 Output",
        AddArea: "Add Area",
        EditArea: "Edit Area",
        AddNextArea: "Add Next Area",
        RCOHDC: "Remaining capacity of hard disk capacity",
        RDOLP: "Remaining date of licence period",
        SODS: "Size of database space",
        ImageName: "Image Name",
        Sessionname: "Session Name",
        Memoryusage: "Memory Usage",
        CPUkernelnumber: "CPU Kernel Number",
        Systemtype: "System Type",
        AlarmStatistics: "Alarm Statistics",
        Company: "Company",
        AllCompany: "All Company",
        AlldeviceType: "All DeviceType",
        Device: "Device",
        StatisticalChartOfAlarmTrend:"Statistical Chart Of Alarm Trend",
        Month:"Month",
        Week:"Week",
        Day:"Day",
        Hour:"Hour",
        Template:"Template",
        Card_Config:"CardConfig",
        Alarm_Model:"Alarm Model",
        GNSS_4E1:"GNSS+4E1 Input",
        T1_TOD:"T1-TOD Ouput",
        PPS_TOD:"PPS-TOD Ouput",
        POFM:"POFM",
        LICENSE_MANAGE:"License Manage",
        LICENSE_KEY:"License Key",
        LICENSE_ENTER:"Please Enter The License Number!",
        LICENSE_TYPE:"License Type",
        PTP_MESSAGE:"PTP Message",
        trackedGnssType: "Current Tracked Gnss Type",
		    positionConfig: "PositionConfig",
        MgmtAddrMode: "MgmtAddr Mode",
        PTPClient: "PTP Client",
        ModuleID: "Module ID",
        PortID: "Port ID",
        SendAnnounce: "SendAnnounce",
        SendSync: "SendSync",
        SendDelayResp: "SendDelayResp",
        SendFollowUp: "SendFollowUp",
        SendSignaling: "SendSignaling",
        SendManage: "SendManage",
        RcvAnnounce: "RcvAnnounce",
        RcvSync: "RcvSync",
        RcvDelayReq: "RcvDelayReq",
        RcvSignaling: "RcvSignaling",
        RcvManage: "RcvManage",
        activestate: "Active State",
        TodOutput: "TOD Output",
        CommonConfig: "Common Config", 
        LEDName: "LED Name", 
        offsetstats: "Offset Stats", 
        ntpClient: "NTP Client", 
        E1INPUTCARD:"E1 Input Card",
        gnssConfigInfo:"GNSS Config Info",
        gnssStateInfo:"GNSS State Info",
        MessageConfig: "Message Config",
        DataDictionary: "Data Dictionary",
        DataDictionaryField: "Data Name",
        DataDictionaryValue: "Data Value",
        DataDictionaryDisEn: "The Data Of English Displaying Name",
        DataDictionaryDisCn: "The Data Of Chinese Displaying Name",
		    AlarmData: "Alarm Data",
        AllDevice: "All Device",
        DEVICE_TYPE:"Device Type",
        GPS_LOCATION:"Gps Location",
        SYS_MODE:"Sys Mode",
        CONFIGURATION_STATE:"Configuration State",
        ACTIVATION_STATE:"Activation State",
        SYSTEM_CONFIG:"System Config",
        FIRMWARE_ARTICLE_NUMBER:"Firmware Article Number",
        FIRMWARE_VERSION:"Firmware Version",
        OSCILLATOR_TYPE:"Oscillator Type",
        CS_TUBE_TYPE:"Cs Tube Type",
        CS_TUBE_SERIAL_NUMBER:"Cs Tube Serial Number",
        ALARM_MASK:"Alarm Mask",
        E1_OUTPUT_CONFIG:"E1 Output Config",
        CODE:"code",
        IDLECODE:"idlecode",
        T1_OUTPUT_CONFIG:"T1 Output Config",
        BUZZER:"buzzer",
        RS_PORT:"RS Port",
        DATA_BIT:"Data Bit",
        PARITY:"Parity",
        SYNC_PPS:"Sync PPS",
        OUTPUT_CONFIG:"Output Config",
        OUTPUT_SQ:"Output Squelch",
        EXP_OUTPUT_FREQUENCY:"Expansion Card Output Frequency",
        FREQUENCY:"Frequency",
        MAIN_CARD_OUTPUT_FREQUENCY:"Main Card Frequency",
        PPS_CONFIG:"PPS Config",
        PPS_INPUT_STATE:"PPS Input State",
        PPS_OUTPUT_CONFIG:"PPS Output Config",
        WIDTH:"Width",
        POLARITY:"Polarity",
        PPS_INPUT_CONFIG:"PPS Input Config",
        OUTPUT_CARD:"Output Card",
        PLUS_SECOND:"Plus Second",
        MINUS_SECOND:"Minus Second",
        synch:"External Second Synchronization",
        close:"close",
        STORAGE_MODE:"Storage Mode",
        WORKING_MODE:"Working Mode",
        DEBUG_MODE:"Debug Mode",
        ENTER:"Enter",
        NOT_ENTER:"Not Enter",
        POSITIVE_LEAP_SECOND:"Positive Leap Second",
        NEGATIVE_LEAP_SECOND:"Negative Leap Second",
        SQUARE_WAVE_FREQUENCY:"Square wave frequency",
        SQUARE_WAVE_SIGNAL:"Square Wave Signal",
        SYNCHRONOUS_STATE:"Synchronous State",
        WORKING_STATE_OF_LASER:"Working State Of Laser",
        LASER_ACTUAL_CURRENT_VALUE:"Laser Actual Current Value",
        ACTUAL_TEMPERATURE_OF_LASER:"Actual Temperature Of Laser",
        LASER_TWO_STAGE_TEMPERATURE_CONTROL_TEMPERATURE:"Laser Two Stage Temperature Control Temperature",
        CESIUM_BUBBLE_TEMPERATURE:"Cesium Bubble Temperature",
        SATURATED_ABSORPTION_SPECTRUM_PD_VOLTAGE:"Saturated Absorption Spectrum PD Voltage",
        CESIUM_FURNACE_WORKING_TEMPERATURE:"Cesium Furnace Working Temperature",
        OV_OF_HV_MODULE_OF_PU:"Output Voltage Of High Voltage Module Of Power Unit",
        CURRENT_OF_HV_MODULE_OF_PU:"Current of high voltage module of power unit",
        OUTPUT_OF_CONSTANT_CURRENT_SOURCE_MODULE:"Output Of Constant Current Source Module",
        OP_OF_MICROWAVE_SIGNAL_SOURCE:"Output Power Of Microwave Signal Source",
        RAMSEY_PATTERN_VOLTAGE:"Ramsey Pattern Voltage",
        CAUSE_OF_SERVO_UNIT_ALARM:"Cause Of Servo Unit Alarm",
        CAUSE_OF_LASER_CIRCUIT_ALARM:"Cause Of Laser Circuit Alarm",
        RUBIDIUM_CLOCK_TAMING_STATE:"Rubidium Clock Taming State",
        TIME_DIFFERENCE_VALUE:"Time Difference Value",
        SYNCHRO_LENGTH:"Synchro Length",
        CRYSTAL_OSCILLATOR_VCV:"Crystal Oscillator Voltage Control Voltage",
        TIME_RELIABLE_SIGN:"Time Reliable Sign"
    }); 
    $translateProvider.translations('ch', {
        MacInfo:"Mac信息",
        LinkSta:"连接状态",
        LinkInfo:"连接信息",
        LinkandMac:"连接和端口",
        MGMtime:"MGM时间",
        MGMuptime:"MGM启动时间",
        Image1:"镜像1",
        Image2:"镜像2",
        BackupImg:"备份镜像",
        NextImg:"下一跳镜像",
        AlarmId : "告警ID",
        AlarmchrId : "告警子ID",
        AlarmLevel : "告警等级",
        Systemtype: "系统类型",
        CPUkernelnumber: "cpu核数",
        ImageName: "映像名称",
        Sessionname: "会话名",
        Memoryusage: "内存使用",
        RCOHDC: "硬盘容量剩余容量",
        RDOLP: "许可证期限剩余日期",
        SODS: "数据库空间占用大小",
        AddArea: "添加一级区域",
        EditArea: "修改区域",
        AddNextArea: "添加下级区域",
        Input1: "输入卡1",
        Input2: "输入卡2",
        PTPoutput: "PTP(输出卡)",
        PTPInput: "PTP(输入卡)",
        NTPoutput: "NTP(输出卡)",
        E1output: "E1(输出卡)",
        COPYTO: "Copy To",
        SHOWALL: "查看全部",
        COPYTO: "复制到",
        delDirection: "删除信号线",
        xxlx: "信号流向:",
        noalarm: "暂无告警",
        pslotport: "请输入槽位和端口",
        UTCTIME: "UTC时间",
        BJTIME: "北京时间",
        qyjx: "区域简写",
        qycj: "区域层级",
        srdk: "输入端口",
        srcw: "输入槽位",
        scdk: "输出端口",
        sccw: "输出槽位",
        ForwardFlowWeight: "向前流权重", 
        ReverseFlowWeight: "向后流权重", 
        CorrectionFrequency: "校正频率",
        PhaseCorrection: "Phase校正",
        ResidualPhaseError: "剩余Phase错误",
        MinimalRTD: "最小的RTD",
        PacketRateGM1: "GM1包速率",
        PacketRateDelay: "包速率延迟",
        ClientConfigState: "客户端配置状态",
        RefStatus: "R参考源状态",
        FLLstate: "FLL状态", 
        GM2addr: "GM2地址", 
        GM2state: "GM2使能", 
        GM1state: "GM1使能", 
        GM1addr: "GM1地址", 
        Common: "共用特征",
        Client: "客户端",
        ConfigManage: "配置管理",
        PortBZ: "端口备注",
        Terminal: "仿真终端",
        baseConfig: "基础配置",
        halfDuplex: "半双工",
        fullDuplex: "全双工",
        slotNumber: "槽位号",
        NtpSlot: "Ntp槽位",
        NtpPort: "Ntp端口",
        cardType: "板卡类型",
        outputSignal: "输出信号",
        slotState: "槽位使能",
        powerState: "电源使能",
        referencePtpin: "参考源类型",
        refStatePtpin: "参考源使能",
        refPriorityPtpin: "参考源优先级",
        refStatusPtpin: "参考源状态",
        inputSourceType: "输入源类型",
        inputSourceState: "输入源使能",
        outputIrigbAcRatio: "IrigAc比",
        outputIrigbConfig: "Irigb配置",
        outputIrigbOffset: "Irigb偏移",
        outputIrigbParity: "Irigb奇偶性",
        outputTodSelect: "Tod选择",
        refStatusType: "参考源类型",
        refStatusFreqSt: "参考源频率使能",
        refStatusFreqWeight: "参考源频率权重",
        refStatusTimeSt: "参考源时间使能",
        refStatusTimeWeight: "参考源时间权重",
        refStatusQlF: "参考源QlF",
        refStatusQlT: "参考源QlT",
        refConfigFP: "参考源配置FP",
        refConfigF: "参考源配置F",
        refConfigTP: "参考源配置TP",
        refConfigT: "参考源配置T",
        refConfigAQL: "参考源配置AQL",
        refConfigFAQL: "参考源配置FAQL",
        refConfigTAQL: "参考源配置TAQL",
        ntpSlotAlarm: "槽位告警",
        ntpSlotCpuMem: "槽位CPU内存",
        ntpSlotHWVersion: "槽位设备硬件版本",
        ntpSlotImage: "槽位镜像",
        ntpSlotLinkStatus: "槽位连接状态",
        ntpSlotMacInfo: "槽位硬件信息",
        ntpSlotTrackStatus: "槽位通道状态",
        ntpSlotVersionInfo: "槽位版本信息",
        ntpSlotBackup: "槽位备份",
        ntpSlotReboot: "槽位重启",
        ntpSlotRestore: "槽位重置",
        ntpPortByteEn: "端口字节使能",
        ntpPortAutokeyEn: "端口Autokey使能",
        ntpPortAutokeyVal: "端口Autokey值",
        ntpPortIpAddr: "端口IP地址",
        ntpPortIpEn: "端口IP使能",
        ntpPortListIp: "端口IP列表",
        ntpPortListMode: "端口列表使能",
        ntpPortMd5En: "端口Md5使能",
        ntpPortMd5Val: "端口Md5值",
        ntpPortMode: "端口模式",
        ntpPortPing: "端口Ping",
        ntpPortPingResult: "端口Ping结果",
        ntpPortBroadcastAddr: "广播地址",
        ntpPortBroadcastCfg: "广播Cfg",
        ntpPortBroadcastEn: "广播使能",
        ntpPortBroadcastTimeInterval: "广播时间区间",
        ntpPortRate: "端口速率",
        ntpPortReset: "端口重置",
        ntpPortResetResult: "端口重置结果",
        ntpMD5keySetting: "MD5key文件设置",
        ntpAutokeyfileSetting: "Autokey文件设置",
        threshold: "阈值",
        status: "状态",
        module: "告警源",
        AlarmStatistics: "告警统计",
        timeDate: "日期",
        IMCStateEvent: "管理卡事件与状态",
        TransientEvent: "瞬态事件",
        InputStateEvent: "输入状态事件",
        ITHStateEvent: "钟卡事件与状态",
        SubrackorIMCNIMCStateEvent: "子架和IMC/NIMC状态事件",
        NIMCEvent: "NIMC事件",
        OutputCardStateEvent: "输出卡事件与状态",
        StateEvent: "事件与状态",
        IMCNIMCStateEvent: "IMC/NIMC事件与状态",
        tconstsec: "时间常数为振荡器",
        autopm: "自动上传PM",
        crc4: "CRC4校验",
        ctieenb: "连续的tie使能",
        currssm: "当前SSM值",
        format: "输入格式",
        measdly: "测量Delay",
        monitor: "输入事件监测",
        prc5MHZ: "PRC 5MHz信号",
        qcutoff: "质量截断",
        sigmode: "信号模块",
        ssmenb: "读取SSM使能",
        ssmpdh: "SSM在PDH系统",
        tconst: "时间常数",
        srveff: "是否影响服务",
        aomerge: "自动输出合并",
        inacttime: "活动时间",
        lclao: "局部自动输出",
        ALWAYS: "总是",
        LOGIN: "登录",
        NEVER: "从不",
        lclbaud: "当地的波特率",
        Y: "是",
        N: "否",
        lclflow: "本地流量",
        lclecho: "本地回显",
        rmtao: "远程自动输出",
        rptall: "报告所有",
        scramble: "争夺通信",
        AIS: "AIS",
        hldact: "保持动作",
        CONTINUE: "继续",
        sabits: "sa位",
        BITS:"位",
        traffic: "交通数据模式",
        trscssm: "同步状态消息",
        INSERT: "插入",
        NOINSERT: "不插入",
        loslog: "输入卡信号日志",
        losalm: "输入卡信号告警",
        NONALM: "无告警",
        cri: "标准",
        rpt: "报告",
        pm: "PM",
        thr: "门槛",
        isqlog: "输入通道日志",
        isqalm: "输入通道告警",
        hslimit: "高限滑",
        bldlmt: "相位限制",
        dsctime: "中断时间",
        hfqlevl: "保持和Freerun质量水平",
        hfqlevlsec: "保持和Freerun质量水平二振荡器",
        manchan: "手动通道",
        mxccn: "CTIE通道数最大",
        pirange: "牵引范围",
        pirangesec: "次级牵引范围振荡器",
        sprdchn: "传播渠道",
        wtrss: "等待时间恢复同步源",
        revert: "反模式",
        syncmde: "同步模式",
        FORCED: "强制",
        systemParameter: "系统参数",
        alarmmode: "告警模块",
        State: "使能",
        Fasttrack: "快捕",
        ON: "打开",
        SQUELCH: "压制",
        ISOLATED_1: "隔离模式",
        imc: "管理口",
        coml: "左口",
        comr: "右口",
        comi: "中间口",
        syncmode: "同步模块",
        refmode: "参考源模块",
        iocstatus: "钟卡状态",
        PTPstatus: "PTP状态",
        netstatus: "网络状态",
        ioccomm: "钟卡间通讯告警状态",
        imccomm: "管理卡/钟卡通讯告警状态",
        iocstate: "钟卡使能",
        INSERV: "正在提供服务",
        OOSRV: "停止提供服务",
        iocmode: "钟卡模块",
        ACTIVE: "激活",
        STANDBY: "备用",
        ACTIVEBY: "主用",
        clkmode: "时钟模式",
        WARMUP: "预热",
        FREERUN: "自由",
        FASTLOCK: "快捕",
        BRIDGING: "过渡",
        HOLDOVER: "守时",
        LOCKED: "锁定",
        clktype: "晶振类型",
        ST3E: "ST3E",
        TYPEI: "TYPEI",
        ST2: "ST2",
        TYPEII: "TYPEII",
        outstatus: "输出模块状态",
        OK: "正常",
        ALM: "报警",
        UNEQUIPPED: "未安装",
        outstate: "输出模块使能",
        frmtype: "输出频率信号类型",
        freeflt: "自由振荡模式输出信号配置",
        holdflt: "守时模式输出信号配置",
        gpsstatus: "gps模块状态",
        mode: "模块",
        pos: "POS",
        elevmask: "俯仰角门限",
        satelliteList: "卫星列表",
        inpstatus: "输入模块状态",
        instate: "输入端口状态",
        MONITOR: "监测",
        qlevel: "质量等级",
        refModel: "参考源模块",
        rqlevel: "rq等级",
        crcena: "CRC使能控制",
        ssmena: "SSM使能控制",
        ssmbit: "SSM位",
        ioc1comm: "钟卡1通讯告警",
        ioc2comm: "钟卡2通讯告警",
        baud: "波特率",
        flow: "流控制",
        NONE: "无",
        SW: "软件",
        HW: "硬件",
        SWHW: "自动",
        ipsubnet: "子网",
        echo: "回显",
        outstatus: "输出状态",
        prsstatus: "PRS状态",
        aid: "aid",
        ntfcncde: "告警级别",
        condtype: "告警编码",
        authen: "认证控制",
        keyid: "认证识别码",
        minpoll: "最短请求时间",
        maxpoll: "最长请求时间",
        preferred: "首选控制",
        rtmstatus: "RTM模块状态",
        rtmstate: "RTM模块使能",
        rtmlbo: "重定时线路增建控制",
        RETIME: "非直通模式",
        CUTTHRU: "直通模式",
        rtmslip: "位滑动允许数量",
        gnssStaPOSMode: "定位模式",
        gnssStaPpsValid: "PPS有效标识",
        gnssStaPpsRef: "PPS参考源",
        gnssStaEngineModel: "通讯模块",
        gpsSatellitePRN: "卫星编号",
        gpsSatelliteNumber: "卫星数量",
        gpsStaCurrentPosition: "当前位置",
        gpsProducer: "模块厂商",
        gpsStaTrackStatue: "跟踪状态",
        gpsSatelliteELEV: "仰角",
        gpsSatelliteIndex: "索引",
        gpsSatelliteAZIM: "方位角",
        gpsSatelliteSNR: "信噪比",
        all: "全部",
        head: "头部",
        tail: "尾部",
        rebootIPC: "重启网络配置",
        restoreIPCConfig: "恢复网络配置",
        factoryIPCConfig: "出厂网络配置",
        backupIPCConfig: "备份网络配置",
        Manual: "手动",
        Auto: "自动",
        apply: "应用",
        noapply: "不应用",
        systemReboot: "系统重启",
        imageInfoIndex: "索引",
        imageVersion: "镜像版本",
        outputSquelchState: "输出压制使能",
        outputPPSState: "输出PPS使能",
        output10MState: "输出10M使能",
        outputrefidleapState: "refidleap使能",
    	ntpServerListEnable: "NTP服务器列表使能",
    	ntpServerAutoKeyEnable: "NTP服务器AutoKey使能",
        ntpServerAutoKeyValue:"NTP服务器AutoKey值",
        ntpServerBroadcastEnable:"NTP服务器广播使能",
        ntpServerBroadcastAddr:"NTP服务器广播地址",
        ntpServerBroadcastInterval:"NTP服务器广播间隔",
        ntpServerMd5Enable:"NTP服务器Md5使能",
        ntpServerMd5Value:"NTP服务器Md5值",
        ntpServerManycastEnable:"NTP服务器多播使能",
        ntpServerManycastAddr:"NTP服务器多播地址",
        ntpServerManycastInterval:"NTP服务器多播间隔",
        ntpServerConfigPortState:"NTP服务器配置端口状态",
        ntpServerConfig:"NTP服务器配置",
        ntpAutoKeyEnable:"NTPAutoKey使能",
        ntpAutoKeyValue:"NTPAutoKey值",
        ntpBroadcastEnable:"NTP广播使能",
        ntpBroadcastAddr:"NTP广播地址",
        ntpBroadcastInterval:"NTP广播间隔",
        ntpEnable:"NTP使能",
        ntpMd5Enable:"NTPMd5使能",
        ntpManycastEnable:"NTP多播使能",
        ntpManycastAddr:"NTP多播地址",
        ntpManycastInterval:"NTP多播间隔",
        refOffsetHistoryShowFlag:"参考源偏移历史查询标志",
        refOffsetHistoryShowNumber :"参考源偏移历史查询数量 ",
        refOffsetHistoryInfo:"参考源偏移历史信息",
        refConfigType:"参考源配置类型",
        refActive:"参考源激活状态",
        refState:"参考源状态",
        refPriority:"参考源优先级",
        refQuality:"参考源质量等级",
        invAssetNum:"设备资产编号",
        invSystemModel:"设备系统类型",
        invPartNum:"设备产品编号",
        invClEINum:"设备通用语言设备识别码",
        invSerial:"设备序列号",
        invHWVersion:"设备硬件版本",
        invSWVersion:"设备软件版本",
        gpsConfigMode:"搜星模式",
        gpsConfigElevMask:"俯仰角门限",
        gpsConfigCableDelay:"馈线补偿",
        gnssConfigMode:"gnss配置模式",
        gnssConfigElevMask:"gnss仰角掩码",
        gnssConfigCableDelay:"gnss链路延",
        gnssConfigTrackMode:"gnss跟踪模式",
        tftpServerAddress:"tftp服务器地址",
        todSource:"跟踪源",
        lcdTimeZone:"时区",
        lcdTimeZonec:"时区偏差",
        activeAlarms:"当前告警数量",
        NMSAlarms:"网管告警",
        Alarm_Tip_Filter:"报警提示器",
        About:"关于网管",
        Help:"帮助文档",
        ref:"参考源",
        systemName:"设备名称",
        systemStatus:"设备状态",
        systemTime:"设置时间",
        systemUptime:"设备启动时间",
        remarks: "备注",
        bordtype: "板卡类型",
        portName: "业务名",
        binding: "绑定",
        deviceType: "设备类型",
        AlldeviceType: "所有类型",
        alarmsNum: "告警数",
        Remove: "移除",
        Cancel: "取消",
        Upload: "上传",
        comment3: "说明3",
        comment2: "说明2",
        comment1: "说明1",
        configName: "配置名称",
        Actions: "完成",
        Progress: "进度",
        Name: "名称",
        Selectupgradefile: "请选择更新的文件",
        English: "英文",
        Chinese: "中文",
        MD5key: "MD5键",
        CurrUtcOffset: "当前UTC偏移",
        TimeSource: "时间源",
        ScaledLogVariance: "比例对数方差",
        TXssm: "发送同步状态信息",
        EthMode: "网络模块",
        PTPnonelist: "无",
        PTPBlacklist: "NTP黑名单",
        PTPWhitelist: "NTP白名单",
        SyncE: "同步以太网",
        SyncEConfig: "同步以太网配置",
        SyncEStatus: "同步以太网状态",
        AutoNegState: "自动发现网络使能",
        Speed: "速度",
        Ipv6Info: "Ipv6信息",
        HWAddr: "硬件地址",
        IpState: "网络使能",
        GeneralStatusMEMload: "内存状态",
        GeneralStatusMEMload: "内存状态",
        GeneralStatusCPUload: "CPU状态",
        clockCurrentTime: "时钟当前时间",
        clockRunningTime: "时钟运行时间",
        clockState: "时钟状态",
        PartNum: "产品编号",
        SerialNum: "序列号",
        CLEINum: "通用语言设备识别码",
        HwNum: "硬件版本号",
        SwNum: "软件版本号",
        FPGAVersion: "FPGA版本号",
        CompatibilityNum: "兼容性标志码",
        refOffsetHistoryTable: "参考源偏移历史记录",
        refConfigTable: "参考源列表",
        AutokeyState: "Autokey使能",
        MD5State: "MD5使能",
        NTPMD5VALUE: "NTPMd5值",
        AUTHENTICA: "验证",
        CONFIG: "配置",
        ALARM_CONFIGSUB: "告警上报",
        PTPProbe: "PTP监测",
        PTPUnicast: "PTP单播",
        PTPMulticast: "PTP多播",
        PTPCommon: "PTP共用特征",
        NTPSTATUS: "NTP状态",
        NTPPROBE: "NTP监测",
        NTPCONFIG: "NTP配置",
        OUPUT: "输出卡",
        VERSION_sync: "版本同步",
        OFFLINE:"离线",
        ONLINE:"在线",
        NE_CONTDE:"网元状态",
        PASSWORDRULE:"密码规则",
        GETLIST:"获取列表",
        P_E_DATAS:"密码过期天数",
        D_I_C_E_CASE:"是否包含英文字母大小写",
        D_I_C_s_c:"是否包含特殊字符",
        W_T_P_COMP:"是否设置密码复杂度",
        PASSWORD_LEN:"设置密码长度",
        D_I_C_Number:"是否包含数字",
        CONFIRM_N_PAS:"确认新密码",
        NEW_PASSWORD:"新密码",
        UPGRADE:"升级",
        REFHISTORY:"参考源历史信息",
        NTPUSER:"NTP用户",
        SERVER:"NTP服务",
        WHITELIST:"NTP白名单",
        BLACKLIST:"NTP黑名单",
        NETWORK:"网络",
        INVENTORYGROUP:"详细目录",
        UPGRADE:"升级",
        IOPUT:"输入输出",
        IMAGE:"镜像",
        BOARDCAST:"广播",
        ALARM_CONFIG:"告警配置",
        ALARM_STATE:"告警状态",
        OTHER:"其他",
        DOWNLOAD:"下载",
        CUR_INFO:"用户信息",
        CUR_STATE:"当前状态",
        CURRENTSHELF:"当前主机",
        INVENTORYINFO:"设备板卡信息",
        TARGETIP:"目标IP",
        FORMATT:"格式二",
        FORMATO:"格式一",
        LOGIN:"登录",
        SAISIVERSION:"浙江赛思",
        PPSTODOUTPUTCARD:"PPS-TOD输出卡",
        E1OUTPUTCARD:"E1输出卡",
        PTPOUTPUTCARD:"PTP输出卡",
        MANAGEMENTNETWORK:"管理网口",
        SAISI:"同步时钟综合网管",
        TOTALE:"共",
        TO_:"跳转到",
        PAGE:'页',
        logSize:'条记录',
        NO_OFFECTVE_SATELLITE:"暂无有效卫星",
        ELEVATION:"仰角",
        AZIMUTH:"方位角",
        HARDWARE:"硬件",
        PRODUCT_NAME:"产品名",
        MANUFCATURER:"制造商",
        QL_VALUE:"QL值",
        QL_CONFIG:"QL配置",
        QL_STATE:"QL状态",
        REFERENCE_STATE:"参考源状态",
        CONFIRM_CLEAR:"确认清除",
        CONFIRM_VIEW:"确认查看",
        REAL_TIME_ALARM:"实时告警",
        SAVE : "保存",
        ADDFIRSITMENU : "添加一级菜单",
        ADDNEXTMENU : "添加下级菜单",
        EDITMENU : "修改菜单",
        LEAFNODE : "是否叶子节点",
        ROUTE : "路径",
        MENULEVEL : "菜单等级",
        MENUDISTRIBUTION : "菜单分配",
        MENUMANAGEMENT : "菜单管理",
        ROLEMANAGEMENT : "角色管理",
        ROLENAME : "角色名称",
        EQUIPMENTDISTRIBUTION : "设备分配",
        ROLE : "角色",
        DEVICEROLE : "设备角色",
        MENUROLE : "菜单角色",
        USERMANAGEMENT : "用户管理",
        OPENBLACKLIST : "打开黑名单",
        OPENWHITELIST : "打开白名单",
        RESTORE : "恢复",
        FACTORYSETTING : "出厂设置",
        DEFAULTSETTING : "默认设置",
        RESTORESETTING : "恢复设置",
        backupConfig : "备份设置",
        ntpList_ENABLE : "NTP列表使能",
        AutokeyTIMESCALE : "Autokey时标",
        Autokey_ENABLE : "Autokey使能",
        MD5TIMESCALE : "MD5时标",
        MD5_ENABLE : "MD5使能",
        PTPNETWORKHWADDR : "PTPMAC地址",
        PTPCLINETLOAD : "PTP客户端载入",
        PTPCLIENTNUM : "PTP客户端数",
        PTPTIMESCALE : "PTP时钟",
        PTPCLOCKACCURACY : "PTP时钟精度",
        PTPCLOCKCLASS : "PTP时钟等级",
        PTPPORTSTATE : "PTP端口状态",
        RUNNINGTIME : "运行时间",
        CURRENTTIME : "当前时间",
        PTPCLOCKSTATE : "PTP时钟状态",
        PTPPROFILE : "PTP配置文件",
        PTPCLOCKID : "PTP时钟ID",
        PTPPORT_ENABLE : "PTP端口使能",
        RATE : "速率",
        DUPLEX : "双工",
        AutoNeg_ENABLE : "自动协商使能",
        SynceQL_ENABLE : "同步以太网质量使能",
        SynceOutQLmode : "同步以太网输出质量模式",
        ESMC_ENABLE : "ESMC模式使能",
        DSCP_ENABLE : "DSCP使能",
        PRIORITY2 : "优先级2",
        PRIORITY1 : "优先级1",
        SERVICEMODE : "服务模块",
        DITHER : "抖动算法",
        NTP_ENABLE : "NTP使能",
        CURRENT:"当前设备",
        CHOOSE:"选择",
        MAINSHELF:"主机框",
        EXPSHELF1:"扩展机框1",
        EXPSHELF2:"扩展机框2",
        EXPSHELF3:"扩展机框3",
        EXPSHELF4:"扩展机框4",
        CARPER:"板卡占用率",
        CPUME:"CPU与内存",
        EXPPER:"槽位占用率",
        VERSIONIN:"版本信息",
        ENABLEOC:"冗余操作",
        ACTIVATE:"激活",
        CHANEG:"切换",
        RESTART:"重启",
        Reboot:"重启",
        Reset:"重置",
        RESTARTXN:"重置性能监测",
        RESTARTC:"重启板卡",
        REFERENCE:"参考源",
        SYNC:"同步",
        CHECK:'查看',
        ALARM:"告警",
        DELETE:'删除',
        CURRENT_USER:"当前用户",
        EXIT:'退出',
        YES:'是',
        NO:'否',
        FTP_SERVER_IP:'FTP服务器IP',
        UPGRADE_F_N_FORMAT:"升级的文件名+扩展名",
        DEVCIE_UPGRADE : "设备升级",
        DEVICE_C_B_R:"设备配置备份与还原",
        FILE:'文件',
        REMOTE_IP:"远端IP",
        CONFIGURATION_FILE:"配置文件",
        ALL_BOARD_CARD:'所有板卡',
        MANAGE_CARD:"管理卡",
        OAM:"管理卡",
        CLOCK_CARD:'钟卡',
        CPMR:"钟卡",
        CLOCK_CARD1:'钟卡1',
        CLOCK_CARD2:'钟卡2',
        BACKUP_TO: "备份至",
        BOARD_CARD:'板卡',
        EXPORT:"导出",
        PERFORMANCE_MONITORING_CONFIGURATION:"性能监测配置",
        PERFORMANCE_FORM : "性能表单",
        LANGUAGE : "语言",
        NETWORK_UPGRADE:"网管升级",
        DEVICE_TESTING : "设备检测",
        MODE:'方式',
        INPUT: "输入",
        TESTING : "检测", 
        SCREENSAVER : "屏保",
        SCREENSAVER_SWITCH : "屏保开关",
        WAKE_PASSWORD_SWITCH : "唤醒密码开关",
        WAITING_TIME : "等待时间",
        WAKE_PASSWORD : "唤醒密码",
        SOUND:'声音',
        SOUND_SWITCH : "声音开关",
        SOUND_INTERVAL : "声音间隔",
        SOUND_RESPONSE_TIME : "单次响应时间",
        PRINT:'打印',
        FRGA_VERSION:"FPGA版本",
        SERIAL_NUMBER:"序列号",
        ClEI_NUMBER:"ClEI编号",
        CARD_TYPE:"卡型号",
        MODULAR:"模块",
        ZCARD_2_CUR_STATE:"钟卡2当前状态",
        ZCARD_1_CUR_STATE:"钟卡1当前状态",
        TARGET_IP: "目标IP",
        NUMBER:'编号',
        VLAN_MODE_ENABLE:"VLAN模式使能",
        AUTO_NEGO_rATE:"自动协商速率",
        AUTO_NEGO_ENABLE:"自动协商使能",
        CURRENT_RATE:"当前速率",
        IP_MODE:"IP模式",
        IP_PORT_STATE: "IP端口状态",
        PORT_1_MODEL: "端口1 业务模式",
        PORT_2_MODEL: "端口2 业务模式",
        FIREWALL_State: "防火墙状态",
        FIREWALL_TYPE: "防火墙类型",
        GATEWAY: "网关",
        DestNetwork : "目标网络",
        MASK :"掩码",
        IP_ADDRESS:"IP地址",
        CARD_1 : '钟卡 1',
        CARD_2 : '钟卡 2',
        MANAGEMENT_CARD : "管理卡",
        REPORT_ENABLEA: "上报使能(all)",
        REPORT_ENABLE: "上报使能",
        DELAY : "延时",
        LEVEL : "等级",
        ALARM_DESC : "告警描述",
        ALARM_ENABLE: "告警使能",
        ALARM_DELAY: "告警延迟",
        ADDRESS : "地址",
        INDEX : "索引",
        MANAGED_ADDRESS_MODE:"管理寻址模式",
        MAX_CLIENT : "最大客户端数",
        DATA_FORMAT : "数据格式",
        NTP_ENABLE : "NTP使能",
        LEAP_SECONDS_SET : "闰秒设置",
        SYSTEM_TIME : "系统时间(UTC)",
        QUALITY_GRADE:"质量等级",
        CRC_STATE: "CRC状态",
        SSM_STATE: "SSM状态",
        SSM_BIT: "SSM位",
        SLOT : "槽位",
        INPUT_CARD : "输入卡",
        PRIORITY : "优先级",
        TTL : "数据生存周期",
        DSCP : "差分服务代码点",
        PacketLimit : "包限制",
        ProbeEnable : "端口使能",
        ServerIP : "服务器IP",
        Interval : "间隔",
        DSCPENABLE : "差分服务代码点使能",
        StatusENABLE : "状态使能",
        Mode : "模式",
        LeapStatus : "闰秒状态",
        StratumLevel : "基准等级",
        RootDispersion : "最大误差分布",
        PacketLoad : "数据包负载",
        Sync : "同步",
        offset : "偏差",
        offsetfw : "偏差(大于0.01 或 小于-0.01)",
        ANN : "通知",
        UnicastClinet : "单播客户端",
        ClockID : "时钟ID",
        Grandmasterip : "最优主时钟IP",
        Grandmasterid : "最优主时钟ID",
        LeaseDuration : "租赁期限",
        Profile : "配置模式",
        TimeScale : "时标",
        Domain : "域",
        SyncLimit  : "同步限制",
        DelayLimit : "延迟限制",
        TwoStep : "二阶",
        UnicastNegotiation : "单播协商",
        AnnounceLimit : "通知限制",
        AlternateMaster : "备用主",
        UnicastLeaseDuration  : "单播租约期限",
        SyncInterval : "同步间隔",
        AnnounceInterval : "通知间隔",
        DelayInterval  : "延时间隔",
        AnnounceTimeout : "通知超时",
        ClientTimeout : "客户端超时",
        GatewayNetxHop : "默认网关/下一(路由)跳",
        ActiveImage  : "激活镜像",
        ActiveVersion : "激活版本",
        imageBackupImage : "备用镜像",
        imageBackupVersion : "备用版本",
        imageCurrentImage : "下次启动镜像",
        imagebootImage : "下次启动镜像",
        outputNTPchangeActiveStatus : "改变当前状态",
        broadcastConfig : "广播配置",
        outputNTPbroadcastState : "广播使能",
        outputNTPbroadcastIP : "广播IP",
        outputNTPbroadcastInterval : "广播间隔",
        outputNTPbroadcastConfig : "广播配置",
        CableDelay : "链路延时",
        FRAME_TYPE : "帧类型",  // todo 
        PORT_ENABLE : "端口使能",
        CURRENT_DEVICE : "当前设备",
        SET : "设置",
        PQL_VALUE : "质量优先级值",
        PQL_STATE :"质量优先级状态",
        ANTENNA_DELAY : "天线延迟",
        TRACKING_MODE : "跟踪模式",
        HEIGHT : "高度",
        LATITUDE : "纬度",
        LONGITUDE:"经度",
        GNSS1_PATTERN : "模式",
        GNSS1_ENABLE : "使能",
        SORT:"排序",
        MAP:"地图",
        ADD:"添加",
        EDIT:"修改",
        SEARCH:"搜索",
        NEXT:"下一页",
        PREVIOUS:"上一页",
        NAMECN:"名称(cn)",
        NAMEEN:"名称(en)",
        OPERATION:"操作",
        NULL_DATA:"暂无数据！",
        PLEASE_SELECT:"请选择",
        activeAlarmId : "告警编号",
        activeAlarmModule : "告警源",
        activeAlarmLevel : "告警等级",
        time : "时间",
        isEnable : "是否启用",
        urgentAlarm : "严重",
        mainAlarm : "主要",
        minorAlarm : "监视",
        EVENT : "事件",
        MAIL:'邮件',
        DISABLE:"禁用",
        ENABLE:'启用',
        BACK:'返回',
        CONFIRM:"确认",
        ALARM_FILTER:"告警过滤",
        SEND:'发送',
        NO_SEND:"不发送",
        ALARM_LOG:"告警日志",
        DEVICE:'设备',
        STATE:"状态",
        BEGIN_TIME:"开始时间",
        END_TIME:"结束时间",
        SHOW_DATE:"展示日期",
        OPERATION_TIME:"操作时间",
        ALARM_BEGIN_TIME:"告警时间",
        ALARM_END_TIME:"告警时间",
        CLEAR_BEGIN_TIME:"清除时间",
        CLEAR_END_TIME:"清除时间",
        CONFIRM_BEGIN_TIME:"确认时间",
        CONFIRM_END_TIME:"确认时间",
        ALARM_REASON:"告警原因",
        ALARM_CONFIRMATION:'告警确认',
        DISAPPEAR:'消失',
        PRODUCE:"产生",
        CLEAR:"清除",
        ALARM_TIME:'告警时间',
        CONFIRM_TIME:'确认时间',
        CLEAR_TIME:'清除时间',
        DESCRIBE:"描述",
        SYSTEM_LOG:'系统日志',
        SYSTEM_NAME:'系统名称',
        MEMORY:"内存",
        OPERATION_LOG:'操作日志',
        USER:'用户',
        NETWORK_LOG:'网管日志',
        ALARM_CONTENT:"告警内容",
        SAFE_LOG:"安全日志",
        PERFORMANCE_LOG:"性能日志",
        TYPE:'类型',
        PORT:'端口',
        VALUE:'值',
        AREA_MANAGE:'区域管理',
        AREA_NAME:'区域名称',
        AREA_ADD:'区域添加',
        DEVICE_MANAGE:'设备管理',
        ALLOCATION : "分配",
        ALREADY_ASSIGEND:"已分配",
        Not_ASSIGNED:"未分配",
        ARER:'区域',
        NE_NAME:"网元名称",
        NE_IP:"网元IP",
        Previous_NE:"上一个网元",
        Next_NE:"下一个网元",
        NE_add:"网元地址",
        NE_DESCRIBE:"网元描述",
        NE_VERSION:"网元版本",
        NE_TIME:"网元时间",
        NE_TYPE:'网元类型',
        NE_PHYSICAL_POSSITION:"网元物理位置",
        NE_SUPPLIER_NAME:"网元供应商名称",
        AREA_CHOOSE:"区域选择",
        Choose_Port:"选择端口",
        Time_Sync:"时间同步",
        Time_Zone:"时区配置",
        Server_Alarm_Threshold:"服务器报警阈值",
        Alarm_Threshold:"报警阈值",
        Database_Config:"数据库配置",
        NE_AND_NETWORK_connection:'网元与网管连接方式',
        NE_LOCAL_NAME:"网元本地名称",
        RECK_FRIENDLY_NAME:"机架友好名称",
        RECK_LOCAL_NAME:"机架本地名称",
        RECK_IDENTIFIER:"机架标识符",
        MAP_CUSTOM:"地图定制",
        MANUAL_BACKUP_ARCHIVE:"手动备份/归档",
        ARCHIVE:'归档',
        BACKUP:'备份',
        RESTORE:"还原",
        TABLE_NAME:"表名",
        SUBCLASS:'子类',
        DATA_DEADLINE:"数据截止日期",
        FILE_PATH:'文件路径',
        BACKUP_ARCHIVE_POLICY:'备份/归档策略',
        MAX_DATA_VOLUME:'最大数据量',
        MAX_STORAGE_MONTH:'最大存储月数',
        BACKUP_TYPE:'备份类型',
        STORAGE_PATH:'存储路径',
        BACKUP_ARCHIVE_RECORDS:"备份/归档记录",
        HARDWARE_VERSION:"硬件版本信息",
        PROCESSOR:"处理器",
        GRAPHICAL:"图形",
        DISK:"磁盘",
        PID:"进程ID",
        CPU:"CPU使用率",
        MEM:"内存使用率",
        VSZ:"虚拟内存大小",
        RSS:"内存大小",
        RUN_STATE:"运行状态",
        START:"启动时间",
        STARTs:"开始",
        STOP:"停止",
        End:"结束",
        RUN_TIME:"运行时间",
        COMMAND:"命令",
        SOFTWARE_PROCESS_INFORMATION:"软件进程信息",
        SOFTWARE_VERSION:"软件版本信息",
        ASSEMBLY:"组件",
        ASSEMBLY_NAME:'组件名称',
        VERSION:'版本',
        DATABASE:'数据库',
        CACHE:"缓存",
        WEB_SERVER:"web服务器",
        REVERSE_PROXY:"反向代理",
        ftp_SERVER:"FTP服务器",
        DEVICE_TOPOLOGY : "设备拓扑图",
        DEVICE_TIME:"设备时间(UTC)",
        DEVICE_TIMEBG:"设备时间(UTC+8)",
        DEVICE_NAME:"设备名称",
        DEVICE_IP:"设备地址",
        REFERENCE_MODEL:"参考模式",
        REFERENCE_Criteria:"参考标准",
        CURRENT_REFERENCE:"当前参考源",
        CLOCK_STATE:"时钟状态",
        ZONCA_1_STATE:"钟卡1状态",
        ZONCA_2_STATE:"钟卡2状态",
        CCStatus:"钟卡状态",
        MACHINE_FRAME:"机框",
        SLOT_NUMBER:"槽位号",
        IO_type:"I/O类型",
        SIGNAL_TYPE:"信号类型",
        REDUNDANCY_ENABLE:"冗余使能",
        MAIN_CARD:"主卡",
        EPISODE_RULES:"前传规则",
        MONITORING_PERIOD : "监测周期(秒)",
        MONITORING_STATE : "监测状态",
        MONITORING_BEGIN_TIME : "监测开始时间",
        MONITORING_END_TIME : "监测结束时间",
        WHETHER_AUTOMATIC_REPORTING:"是否自动上报",
        ORDER:'指令',
        USERNAME:'用户名',
        PASSWORD:"密码",
        Company: "公司",
        AllCompany: "所有公司",
        Device: "设备",
        StatisticalChartOfAlarmTrend:"告警趋势统计图表",
        Month:"月",
        Week:"周",
        Day:"日",
        Hour:"时",
        Template:"模板",
        Card_Config:"卡配置",
        Alarm_Model:"告警模版",
        GNSS_4E1:"GNSS+4E1输入卡",
        T1_TOD:"T1-TOD输出卡",
        PPS_TOD:"PPS-TOD输出卡",
        POFM:"PTP输出卡",
        LICENSE_MANAGE:"许可证管理",
        LICENSE_KEY:"许可证号",
        LICENSE_ENTER:"请输入许可证号！",
        LICENSE_TYPE:"许可证类型",
        PTP_MESSAGE:"PTP报文",
        positionConfig: "位置配置",
        trackedGnssType: "跟踪卫星类型",
        MgmtAddrMode: "单播/多播",
        PTPClient: "PTP客户端",
        ModuleID: "模式ID",
        PortID: "端口ID",
        SendAnnounce: "发送Announce",
        SendSync: "发送Sync",
        SendDelayResp: "发送DelayResp",
        SendFollowUp: "发送FollowUp",
        SendSignaling: "发送Signaling",
        SendManage: "发送Manage",
        RcvAnnounce: "接收Announce",
        RcvSync: "接收Sync",
        RcvDelayReq: "接收DelayResp",
        RcvSignaling: "接收Signaling",
        RcvManage: "接收Manage",
        activestate: "激活状态",
        TodOutput: "TOD输出",
        CommonConfig: "通用配置",    
        LEDName: "LED名称",   
        offsetstats: "偏差统计",  
        ntpClient: "NTP客户端", 
        E1INPUTCARD:"E1输入卡", 
        gnssConfigInfo:"卫星配置信息",
        gnssStateInfo:"卫星状态信息",               
        MessageConfig: "报文配置",
        DataDictionary: "数据字典",
        DataDictionaryField: "数据名",
        DataDictionaryValue: "实际值",
        DataDictionaryDisEn: "英文展示名称",
        DataDictionaryDisCn: "中文展示名称",
        AlarmData: "告警数据",
        AllDevice: "所有设备",
        DEVICE_TYPE:"设备类型",
        GPS_LOCATION:"GPS接收机坐标",
        SYS_MODE:"系统模式",
        CONFIGURATION_STATE:"配置状态",
        ACTIVATION_STATE:"激活状态",
        SYSTEM_CONFIG:"系统配置",
        FIRMWARE_ARTICLE_NUMBER:"固件编号",
        FIRMWARE_VERSION:"固件版本",
        OSCILLATOR_TYPE:"振荡器类型",
        CS_TUBE_TYPE:"铯电子管型号",
        CS_TUBE_SERIAL_NUMBER:"铯电子管序列号",
        ALARM_MASK:"告警屏蔽",
        E1_OUTPUT_CONFIG:"E1输出配置",
        CODE:"编码",
        IDLECODE:"空闲码",
        T1_OUTPUT_CONFIG:"T1输出配置",
        BUZZER:"蜂鸣器",
        RS_PORT:"RS 端口",
        DATA_BIT:"数据位",
        PARITY:"奇偶校验",
        SYNC_PPS:"PPS输入同步",
        OUTPUT_CONFIG:"输出配置",
        OUTPUT_SQ:"输出静噪",
        EXP_OUTPUT_FREQUENCY:"扩展卡输出频率",
        FREQUENCY:"频率",
        MAIN_CARD_OUTPUT_FREQUENCY:"主卡输出频率",
        PPS_CONFIG:"PPS配置",
        PPS_INPUT_STATE:"PPS输入状态",
        PPS_OUTPUT_CONFIG:"PPS输出配置",
        WIDTH:"脉宽",
        POLARITY:"极性",
        PPS_INPUT_CONFIG:"PPS输入配置",
        OUTPUT_CARD:"输出卡",
        PLUS_SECOND:"加秒",
        MINUS_SECOND:"减秒",
        synch:"外秒同步",
        close:"关闭",
        STORAGE_MODE:"存储模式",
        WORKING_MODE:"工作模式",
        DEBUG_MODE:"调试模式",
        ENTER:"进入",
        NOT_ENTER:"不进入",
        POSITIVE_LEAP_SECOND:"正闰秒",
        NEGATIVE_LEAP_SECOND:"负闰秒",
        SQUARE_WAVE_FREQUENCY:"方波频率",
        SQUARE_WAVE_SIGNAL:"方波信号相位",
        SYNCHRONOUS_STATE:"同步状态",
        WORKING_STATE_OF_LASER:"激光器所处工作状态",
        LASER_ACTUAL_CURRENT_VALUE:"激光器实际电流值",
        ACTUAL_TEMPERATURE_OF_LASER:"激光器实际温度值",
        LASER_TWO_STAGE_TEMPERATURE_CONTROL_TEMPERATURE:"激光二级温控温度",
        CESIUM_BUBBLE_TEMPERATURE:"铯泡温度",
        SATURATED_ABSORPTION_SPECTRUM_PD_VOLTAGE:"饱和吸收谱PD电压",
        CESIUM_FURNACE_WORKING_TEMPERATURE:"铯炉工作温度",
        OV_OF_HV_MODULE_OF_PU:"电源单元高压模块输出电压",
        CURRENT_OF_HV_MODULE_OF_PU:"电源单元高压模块当前电流",
        OUTPUT_OF_CONSTANT_CURRENT_SOURCE_MODULE:"恒流源模块输出电流",
        OP_OF_MICROWAVE_SIGNAL_SOURCE:"微波信号源输出功率",
        RAMSEY_PATTERN_VOLTAGE:"Ramsey花样电压",
        CAUSE_OF_SERVO_UNIT_ALARM:"伺服单元告警原因",
        CAUSE_OF_LASER_CIRCUIT_ALARM:"激光电路告警原因",
        RUBIDIUM_CLOCK_TAMING_STATE:"铷钟驯服状态",
        TIME_DIFFERENCE_VALUE:"时差值",
        SYNCHRO_LENGTH:"同步时长",
        CRYSTAL_OSCILLATOR_VCV:"晶振压控电压",
        TIME_RELIABLE_SIGN:"时间可靠标志"
    });
    $translateProvider.preferredLanguage('ch');
    $translateProvider.useSanitizeValueStrategy('escape');
}]);