@h8080 = 192.168.92.170:8080

### 获取区域信息 
PUT /nms/spring/device/update23 HTTP/1.1
Host: {{h8080}}
Content-Type: application/json;charset=UTF-8


{"roleName":"1","roleDesc":"2","deviceList":[{"id":"3745e4df-11f6-4565-9df8-0a06d71e4a15"}]}



