"{
""
code "": 100000,
    ""
pageObject "": ""
配置管理 - 网元配置 "",
    ""
data "": "" [{\ ""
    aid\ "": \ ""
    BSRCU1\ "", \ ""
    sateleth\ "": \ ""
    5 #0-10# false\ "", \ ""
    satnumth\ "": \ ""
    2 #0-8# false\ "", \ ""
    scardtype\ "": \ ""
    GPS# GLOGPS | GPS | BEIDOU | NONE# false\ "", \ ""
    tbase\ "": \ ""
    NONE# GPS | GLO | BD | NONE# false\ "", \ ""
    workmode\ "": \ ""
    NONE# DUAL | GPS | GLO | BD | NONE# false\ "" }, {\ ""
    aid\ "": \ ""
    BSRCU2\ "", \ ""
    sateleth\ "": \ ""
    5 #0-10# false\ "", \ ""
    satnumth\ "": \ ""
    2 #0-8# false\ "", \ ""
    scardtype\ "": \ ""
    GPS# GLOGPS | GPS | BEIDOU | NONE# false\ "", \ ""
    tbase\ "": \ ""
    NONE# GPS | GLO | BD | NONE# false\ "", \ ""
    workmode\ "": \ ""
    NONE# DUAL | GPS | GLO | BD | NONE# false\ "" }]
""
}
"