{"name":"首页","id":"index","parentId": "",},
{"name":"物理拓扑","id":"index-physics","parentId": "index",},
{"name":"查看","id":"index-physics_view","parentId": "index-physics",},
{"name":"操作","id":"index-physics_operation","parentId": "index-physics",},
{"name":"管理","id":"index-physics_manage","parentId": "index-physics",},


{"name":"告警列表","id":"index-warningList","parentId": "index",},
{"name":"查看","id":"index-warningList_view","parentId": "index-warningList",},
{"name":"操作","id":"index-warningList_operation","parentId": "index-warningList",},

{"name":"拓扑管理","id":"topology","parentId": "",},

{"name":"物理拓扑","id":"topology-physics","parentId": "topology",},
{"name":"查看","id":"topology-physics_view","parentId": "topology-physics",},
{"name":"操作","id":"topology-physics_operation","parentId": "topology-physics",},
{"name":"管理","id":"topology-physics_manage","parentId": "topology-physics",},
{"name":"逻辑拓扑","id":"topology-logic","parentId": "topology",},

{"name":"查看","id":"topology-logic_view","parentId": "topology-logic",},
{"name":"操作","id":"topology-logic_operation","parentId": "topology-logic",},
{"name":"管理","id":"topology-logic_manage","parentId": "topology-logic",},

{"name":"网管拓扑","id":"topology-net","parentId": "topology",},
{"name":"查看","id":"topology-net_view","parentId": "topology-net",},
{"name":"操作","id":"topology-net_operation","parentId": "topology-net",},
{"name":"管理","id":"topology-net_manage","parentId": "topology-net",},


{"name":"告警列表","id":"topology-warningList","parentId": "topology",},
{"name":"查看","id":"topology-warningList_view","parentId": "topology-warningList",},
{"name":"操作","id":"topology-warningList_operation","parentId": "topology-warningList",},
{"name":"拓扑信息统计","id":"topology-statistics","parentId": "topology",},
{"name":"配置管理","id":"configure","parentId": "",},
{"name":"网元配置","id":"configure-config","parentId": "configure",},
{"name":"查看","id":"configure-config_view","parentId": "configure-config",},
{"name":"操作","id":"configure-config_operation","parentId": "configure-config",},
{"name":"网元管理","id":"configure-manage","parentId": "configure",},
{"name":"查看","id":"configure-manage_view","parentId": "configure-manage",},
{"name":"操作","id":"configure-manage_operation","parentId": "configure-manage",},
{"name":"配置信息统计","id":"configure-statistics","parentId": "configure",},


{"name":"告警管理","id":"warning","parentId": "",},
{"name":"当前告警","id":"warning-current","parentId": "warning",},
{"name":"查看","id":"warning-current_view","parentId": "warning-current",},
{"name":"操作","id":"warning-current_operation","parentId": "warning-current",},
{"name":"历史告警","id":"warning-history","parentId": "warning",},
{"name":"告警处理","id":"warning-handle","parentId": "warning",},
{"name":"查看","id":"warning-handle_view","parentId": "warning-handle",},
{"name":"操作","id":"warning-handle_operation","parentId": "warning-handle",},


{"name":"告警屏蔽","id":"warning-mask","parentId": "warning",},
{"name":"查看","id":"warning-mask_view","parentId": "warning-mask",},
{"name":"操作","id":"warning-mask_operation","parentId": "warning-mask",},
{"name":"告警统计","id":"warning-statistics","parentId": "warning",},
{"name":"性能管理","id":"performance","parentId": "",},
{"name":"当前性能","id":"performance-current","parentId": "performance",},
{"name":"历史性能","id":"performance-history","parentId": "performance",},
{"name":"性能设置","id":"performance-setting","parentId": "performance",},
{"name":"查看","id":"performance-setting_view","parentId": "performance-setting",},
{"name":"操作","id":"performance-setting_operation","parentId": "performance-setting",},
{"name":"性能统计","id":"performance-statistics","parentId": "performance",},
{"name":"运维管理","id":"operation","parentId": "",},
{"name":"数据统计","id":"operation-datas","parentId": "operation",},
{"name":"拓扑信息统计","id":"operation-datas-topology","parentId": "operation-datas",},
{"name":"配置信息统计","id":"operation-datas-configure","parentId": "operation-datas",},
{"name":"告警统计","id":"operation-datas-warning","parentId": "operation-datas",},
{"name":"性能统计","id":"operation-datas-performance","parentId": "operation-datas",},
{"name":"用户统计","id":"operation-datas-user","parentId": "operation-datas",},
{"name":"日志统计","id":"operation-datas-log","parentId": "operation-datas",},
{"name":"年度报表","id":"operation-year","parentId": "operation",},
{"name":"运维调整报表","id":"operation-year-adjust","parentId": "operation-year",},
{"name":"用户活跃度统计","id":"operation-year-activity","parentId": "operation-year",},
{"name":"设备告警统计","id":"operation-year-warning","parentId": "operation-year",},
{"name":"综合分析","id":"operation-allocation","parentId": "operation",},
{"name":"设备故障型号分析","id":"operation-allocation-type","parentId": "operation-allocation",},
{"name":"设备故障厂商分析","id":"operation-allocation-vendor","parentId": "operation-allocation",},
{"name":"设备性能报表","id":"operation-allocation-performance","parentId": "operation-allocation",},
{"name":"温度影响故障分析","id":"operation-allocation-temperature","parentId": "operation-allocation",},
{"name":"调整记录","id":"operation-adjust","parentId": "operation",},
{"name":"查看","id":"operation-adjust_view","parentId": "operation-adjust",},
{"name":"操作","id":"operation-adjust_operation","parentId": "operation-adjust",},
{"name":"环境管理","id":"operation-environment","parentId": "operation",},
{"name":"查看","id":"operation-environment_view","parentId": "operation-environment",},
{"name":"操作","id":"operation-environment_operation","parentId": "operation-environment",},
{"name":"系统管理","id":"system","parentId": "",},
{"name":"安全管理","id":"system-security","parentId": "system",},

{"name":"用户管理","id":"system-security-user","parentId": "system-security",},
{"name":"查看","id":"system-security-user_view","parentId": "system-security-user",},
{"name":"操作","id":"system-security-user_operation","parentId": "system-security-user",},
{"name":"管理","id":"system-security-user_manage","parentId": "system-security-user",},

{"name":"权限管理","id":"system-security-role","parentId": "system-security",},
{"name":"查看","id":"system-security-role_view","parentId": "system-security-role",},
{"name":"操作","id":"system-security-role_operation","parentId": "system-security-role",},
{"name":"管理","id":"system-security-role_manage","parentId": "system-security-role",},
{"name":"用户统计","id":"system-security-statistics","parentId": "system-security",},
{"name":"系统参数","id":"system-security-parameter","parentId": "system-security",},
{"name":"查看","id":"system-security-parameter_view","parentId": "system-security-parameter",},
{"name":"操作","id":"system-security-parameter_operation","parentId": "system-security-parameter",},
{"name":"目录管理","id":"system-security-menu","parentId": "system-security",},
{"name":"查看","id":"system-security-menu_view","parentId": "system-security-menu",},
{"name":"操作","id":"system-security-menu_operation","parentId": "system-security-menu",},
{"name":"日志管理","id":"system-log","parentId": "system",},
{"name":"安全日志","id":"system-log-security","parentId": "system-log",},
{"name":"操作日志","id":"system-log-operation","parentId": "system-log",},
{"name":"系统日志","id":"system-log-system","parentId": "system-log",},
{"name":"日志统计","id":"system-log-allocation","parentId": "system-log",},
{"name":"接口管理","id":"system-interface","parentId": "system",},
{"name":"查看","id":"system-interface_view","parentId": "system-interface",},
{"name":"操作","id":"system-interface_operation","parentId": "system-interface",},
{"name":"网管检测","id":"system-monitor","parentId": "system",},
{"name":"系统信息","id":"system-monitor-infos","parentId": "system-monitor",},
{"name":"查看","id":"system-monitor-infos_view","parentId": "system-monitor-infos",},
{"name":"操作","id":"system-monitor-infos_operation","parentId": "system-monitor-infos",},
{"name":"数据库管理","id":"system-monitor-database","parentId": "system-monitor",},
{"name":"查看","id":"system-monitor-database_view","parentId": "system-monitor-database",},
{"name":"操作","id":"system-monitor-database_operation","parentId": "system-monitor-database",},
{"name":"远程维护","id":"system-monitor-remote","parentId": "system-monitor",},
{"name":"查看","id":"system-monitor-remote_view","parentId": "system-monitor-remote",},
{"name":"操作","id":"system-monitor-remote_operation","parentId": "system-monitor-remote",},
{"name":"帮助","id":"help","parentId": "",},
{"name":"知识库","id":"help-knowledge","parentId": "help",},
{"name":"查看","id":"help-knowledge_view","parentId": "help-knowledge",},
{"name":"操作","id":"help-knowledge_operation","parentId": "help-knowledge",},
{"name":"站点详情","id":"help-station","parentId": "help",},
{"name":"查看","id":"help-station_view","parentId": "help-station",},
{"name":"操作","id":"help-station_operation","parentId": "help-station",},
{"name":"区域详情","id":"help-area","parentId": "help",},
{"name":"查看","id":"help-area_view","parentId": "help-area",},
{"name":"操作","id":"help-area_operation","parentId": "help-area",},
{"name":"设备详情","id":"help-device","parentId": "help",},
{"name":"查看","id":"help-device_view","parentId": "help-device",},
{"name":"操作","id":"help-device_operation","parentId": "help-device",},
{"name":"操作手册","id":"help-operation","parentId": "help",},
{"name":"在线手册","id":"help-online","parentId": "help",},




$.each(a,function(oi,ov){
 
})


